### ISSUE TITLE
python 的关键字 self 没有颜色

### ISSUE THREAD

**Issue by Ihindng** [fisheva/Eva-Theme#1]

**Comment by fisheva** [comment]
很抱歉这么晚才回复!  0.1.13版已更新.
我还不会写Python, 收到你的issues后除了self, 把Python的其他关键字也都检查了遍, 应该都区分上色了.
欢迎继续提issue! 不过你大概已经弃坑了吧_(:з」∠)_

**Comment by Ihindng** [comment]
没弃坑，谢谢。还是你这个主题比较好看
