### ISSUE TITLE
中文字体显示不明显

### ISSUE THREAD

**Issue by ramen06** [fisheva/Eva-Theme#100]
![image](https://github.com/fisheva/Eva-Theme/assets/111961825/34600c07-ccb8-4d82-b956-0aa6c560b000)
如上图, 中文字体浅灰色在背景下有点太淡了, 而且和注释的区分也不太明显. 能否将字体加粗或者换深一点的颜色?

**Comment by ramen06** [comment]
还有注释里的斜体中文看着有点...太花了?

**Comment by fisheva** [comment]
中文字体太花, 这个应该和您的字体设置有关, 我的中文字体是微软雅黑, 看着挺好的...
![image](https://github.com/fisheva/Eva-Theme/assets/17448419/a238ea52-0c19-49f8-95b2-aeae593e44de)

然后您图中的中文字体太浅问题, 你这是JSX吧, 正常HTML标签里的中文字体颜色是和变量名颜色一样的, 在JSX里为了不让JSX中的普通文字颜色干扰到变量名查看, 所以做了淡化处理, 就有点接近注释颜色了. 

如果不是JSX, 你提供下文件类型和源码, 我本地测试下.

**Comment by ramen06** [comment]
[新投稿模板latex.zip](https://github.com/fisheva/Eva-Theme/files/11888986/latex.zip)
在写中文latex下遇到这个问题, 主文件是template1019.tex
第二个问题换字体解决了, 感谢!

**Comment by fisheva** [comment]
开始普通文字设置成#888是为了和变量颜色作区分
![image](https://github.com/fisheva/Eva-Theme/assets/17448419/fea96b9e-00a5-4ace-82c1-20d83ddeb1f2)

已按您说的做了调整, 请升级到2.1.4查看. 现在latax普通文字和html标签里的文字颜色相同了, 不过就和变量颜色区分不开了.
