### ISSUE TITLE
vscode-jupyter color issue

### ISSUE THREAD

**Issue by yuuuxt** [fisheva/Eva-Theme#101]
### Screenshot

如下是default light+ theme的效果: 
1. hover on cell, 左边的indicator颜色区别于背景
![image](https://github.com/fisheva/Eva-Theme/assets/3153534/f97334b8-d9ed-4a9a-b190-67607cc5386e)
2. 按shift多选cell, 选中的cell有额外的底色
![image](https://github.com/fisheva/Eva-Theme/assets/3153534/0b31db00-a2b5-4d96-9993-4243cdacd381)

(这两点在目前的主题中没有体现, 相当于没有视觉反馈)
![image](https://github.com/fisheva/Eva-Theme/assets/3153534/467ad2f0-5dc0-4e36-bac0-4db86785ba32)
![image](https://github.com/fisheva/Eva-Theme/assets/3153534/0941ddf5-edc7-4174-aa83-890e70d1434e)

### Code Snippet

1. 安装vscode-jupyter
2. 任意新建notebook, 创建几个cell即可.

**Comment by fisheva** [comment]
抱歉, 回复晚了。

用排除法找出了影响这个hover和多选颜色的API是 'list.inactiveSelectionBackground'
![20230804102813](https://github.com/fisheva/Eva-Theme/assets/17448419/48cd872a-1dcd-4070-b6ba-453716288a2d)
![20230804102921](https://github.com/fisheva/Eva-Theme/assets/17448419/13b4ec0d-2585-450d-8474-9e5b1c20a9d5)

顺带一提, 影响代码块颜色的API是 "sideBar.background"
![20230804103321](https://github.com/fisheva/Eva-Theme/assets/17448419/fc033ca2-35de-44a5-831b-77a9a4d6fe8f)

但很遗憾, 我没法专为这个插件的使用去修改这2个API颜色, 因为这会同时改变Eva Theme的文件栏颜色风格。这个问题算是jupyter插件选取的颜色API和Eva Theme有冲突, 如果jupyter插件这里选取的是"editor.selectionBackground"API颜色, 体验就还可以。
![20230804105645](https://github.com/fisheva/Eva-Theme/assets/17448419/f456a838-9dca-42f1-959f-062b10935571)
![20230804105806](https://github.com/fisheva/Eva-Theme/assets/17448419/ceb0fdf2-53f0-4065-945b-66c9b53d1571)

最简单的解决办法, 您可以在VSCode的settings.json里自行修改这些API的颜色, 在settings.json里写入

    "workbench.colorCustomizations": {
        "[Eva Light]": {
             // "sideBar.background": "#E1E4EB",
             "list.inactiveSelectionBackground": "#0065FF3F",
             // "editor.selectionBackground": "#0065FF3F",
        },
    },

**Comment by yuuuxt** [comment]
my update for reference (not only for this notebook issue, but also for some other tweaks) : 
```
"[Eva Light]": {
      "activityBar.background": "#E1E4EB",
      "sideBarSectionHeader.background": "#E1E4EB",
      "list.inactiveSelectionBackground": "#CFD2D98C",
      "editorGroupHeader.tabsBorder": "#EBEEF5",
      "tab.border": "#E1E4EB",
      "sideBar.border": "#E1E4EB",
    },
```

**Comment by fisheva** [comment]
Sorry，I copied your settings above into my VSCode settings.json, I found every setting changed the interface style, so I can't add them into Eva Theme.

**Comment by yuuuxt** [comment]
> Sorry，I copied your settings above into my VSCode settings.json, I found every setting changed the interface style, so I can't add them into Eva Theme.

Sure, I was just sharing all my tweaks of the theme. The ones that do affect this specific issue are mentioned in your reply above. Thanks for your work!
