### ISSUE TITLE
new features requests

### ISSUE THREAD

**Issue by vanhp** [fisheva/Eva-Theme#102]
Request for 
- dark bold italic 
- darker background on text area so it easier to read the text
- support for Julia language

**Comment by fisheva** [comment]
@vanhp Please update Eva Theme to 2.1.6 version. 

  - dark bold italic **√**
  - <font color="#999999">~darker background on text area so it easier to read the text~</font>
  - support for Julia language **√** 

VSCode's support for Julia is not very comprehensive, and the scope value differentiation of many keywords is not detailed, so the display effect of Eva Theme is not as good as languages like JS.

For the second request, you can refer to [issue 8](https://github.com/fisheva/Eva-Theme/issues/8).

**Comment by vanhp** [comment]
Thank for the dark bold italic and support for Julia. 
As for darker background I've just used the setting you provide on issue 8. It work great for me. 

I still think you should have 2 versions one slightly lighter and one slightly darker :+1:
