### ISSUE TITLE
左侧的菜单的栏增加一下对比度

### ISSUE THREAD

**Issue by zhangjinlibra** [fisheva/Eva-Theme#103]
最左侧菜单栏的选中和未选择的对比不是很明显，每次点击菜单需要仔细看一下

**Comment by fisheva** [comment]
@zhangjinlibra 请更新Eva Theme (2.2.2)，略微提高了选中的背景色。如果您感觉还不够，可以在setting.json里添加以下文字进行自定义

```json
"workbench.colorCustomizations": {
      "[Eva Dark]": {
		"list.activeSelectionBackground": "#598def3f",
		"list.inactiveSelectionBackground": "#598def3f", 
      },
}
```

解释下为什么不愿把这个文件选中背景色调的很明显：下面是我们的工作界面，红框部分是主编码区，编码时，用户的视线和主注意力都集中在红框区域。为了追求沉浸式编程体验，Eva Theme对红框以外元素的配色原则是： 不显眼不吸引注意力，视线移过来时，又能看清。
![20231120170310](https://github.com/fisheva/Eva-Theme/assets/17448419/98ac8def-6b36-4a1a-9699-77a7160cd8ae)
