### ISSUE TITLE
Contrast between terminal and open file

### ISSUE THREAD

**Issue by akanz1** [fisheva/Eva-Theme#104]
First of all, thank you for this amazing theme, i really enjoy using it during daytime!

Is it possible to increase the contrast or have a subtle line separating the code view from the terminal? I have my terminal open to the left and have a hard time dragging it larger as there is no clear indication where the terminal ends and where the code begins.

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/41de7f68-8758-4da7-bbf2-49abab854c3f)

When hovering with the mouse the line to drag appears, but finding the correct spot is not always easy and takes a moment.

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/e63af2eb-de7c-48dd-804a-ae49444e99a9)

For the filetree, the debug console etc. the contrast is enough to distinguish the border

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/6c3d431d-21b4-4bae-82fb-f52c9253aa18)

and other extensions also have a bit of a color difference and/or a light line to see where to drag:

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/8359b30f-5d30-4805-9ba4-fdb4d18eb876)

**Comment by fisheva** [comment]
@akanz1 Hi, before answering your question, I have two doubts.

1, In fact, there is a thin gray separating line between code view and terminal, which is not very obvious, but there it is.

![20231122102056](https://github.com/fisheva/Eva-Theme/assets/17448419/98840375-2039-4222-a040-cd220b0a22fd)

But in your first screenshot, I didn't see this separating line?

![screenshot-1](https://user-images.githubusercontent.com/51492342/284516806-41de7f68-8758-4da7-bbf2-49abab854c3f.png)

2, When hovering with the mouse the line to drag appears, the line color should be blue.
![20231122102808](https://github.com/fisheva/Eva-Theme/assets/17448419/ae90d3c4-110f-4abe-9e8b-efa99759b29d)

But in your second screenshot, the line shows as another color.

![screenshot-2](https://user-images.githubusercontent.com/51492342/284516856-e63af2eb-de7c-48dd-804a-ae49444e99a9.png)

---

Here is my answer. Three terminal positions, the separating line between code view and terminal share a same API `"panel.border": "#E1E4EB"`. If the APIs of the three locations can be distinguished, I would be happy to set the left separating line color `"panel.border": "#CED1D7"`, which is the same color as the code indent guide line.

![企业微信截图_20231122112321](https://github.com/fisheva/Eva-Theme/assets/17448419/2baeeba6-24e3-4979-8557-09e325750794)

But it can not. Most user use terminal's default bottom location. If I set `"panel.border": "#CED1D7"`, it appears ugly.

![企业微信截图_20231122113634](https://github.com/fisheva/Eva-Theme/assets/17448419/3a2addb9-66b0-48a3-b117-048d2570444c)

So I suggest you add the following text in setting.json for local customization.

```
"workbench.colorCustomizations": {
      "[Eva Light]": {
		"panel.border": "#CED1D7"`,
      },
}
```

---

@akanz1 I found you are the first and only person currently sponsoring me. Thanks so much! That's very nice of you!

**Comment by akanz1** [comment]
Thank you for the detailed reply, that's a good idea to set a value in my personal settings.

I tried applying your suggestion but it only affects the border when the terminal is at the bottom

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/fc90bb9c-a008-485b-b1ac-db3d61d4e3f1)

with same settings when i move the terminal to the side it doesnt work

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/4f790494-efcc-467c-8e15-863481081acc)

I went through all the [panel/section](https://code.visualstudio.com/api/references/theme-color#panel-colors) settings but they only work if the terminal is at the bottom.

What works is setting `"sideBar.border": "#e1e4eb"`. 

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/980e1ea5-614b-46d3-82ba-0903faa88ba8)

This also puts a 1 pixel witdth gap on the right side, which is a bit ugly but barely noticable

![image](https://github.com/fisheva/Eva-Theme/assets/51492342/58efa238-6aa8-4f25-8239-c91508debd29)

**Comment by fisheva** [comment]
That is really strange.
![企业微信截图_20231122170931](https://github.com/fisheva/Eva-Theme/assets/17448419/78c19b93-00f9-4a0d-9515-6a20299f1f98)

 Anyway, It's glad to hear your problem has been resolved.
