### ISSUE TITLE
C++的宏和变量没有被着色

### ISSUE THREAD

**Issue by kedaya1207** [fisheva/Eva-Theme#105]
C/C++代码的宏和变量没有颜色，请问是bug吗
![image](https://github.com/fisheva/Eva-Theme/assets/87792978/d5f008e7-ae05-43ec-a39e-f7acb348c480)

**Comment by kedaya1207** [comment]
然后我发现如果是c语言的话宏就可以被着色，而c++的话宏就不会被着色，我觉得这应该是个bug
![image](https://github.com/fisheva/Eva-Theme/assets/87792978/0e8ca08b-df64-4240-95af-cc8dbbe53c99)
![image](https://github.com/fisheva/Eva-Theme/assets/87792978/2205c448-2a04-4a97-a915-df7a69ebe267)

**Comment by fisheva** [comment]
请把2边的代码都贴一下，我日常不写C，C++，应该是遗漏

**Comment by kedaya1207** [comment]
代码图里有，其实就是随便写一个宏的定义都可以。比如#define AA 2;
在C语言里面就可以被着色，在cpp里面不会被着色

**Comment by fisheva** [comment]
我想起为什么把C语言里的宏指定为数字黄了: 当初在给C语言着色时，并不理解宏的定义，只是看到这样一个例句，让我以为AA是数字常量，和AA相同类型的代码都是数字常量。刚去查了下宏的定义，觉得和函数的概念或功能很接近，于是统一改成了函数蓝。请更新Eva Theme到2.3.4

#define AA 2;

**Comment by kedaya1207** [comment]
好的，我已经更新到了2.3.4，宏已经能够正确着色了，感谢您的反馈。
但是如您所说，我个人认为函数蓝不是很合适，因为在某些情况下它看起来会很怪，如下图
![image](https://github.com/fisheva/Eva-Theme/assets/87792978/08031c5d-3548-4a82-9a24-22967ad7ac57)
这里的宏只是作为一个数字常量参数放在函数中，但是却看起来像会调用两次函数
我个人认为可以您可以参考Visual Studio对C/C++的配色，将它换成紫色或其他颜色，如果您不想再加入其他颜色，我个人认为可以和nullptr一个颜色，如下图
![image](https://github.com/fisheva/Eva-Theme/assets/87792978/afb058bf-7a0e-419d-9140-3a2e0cd35ff9)
这是我的个人意见，无论是否采纳我都衷心感谢您的阅读和反馈:)

**Comment by fisheva** [comment]
紫色在Eva Theme里有了特定的含义：与布尔值或代码控制流程(if for return)相关。

刚刚把宏改回了变量颜色(2.3.5)，综合来看 还是视为一个变量最符合代码语义。

**Comment by kedaya1207** [comment]
好的，感谢您的回复，我认为这个问题可以关闭了
