### ISSUE TITLE
git 更改视图下，注释不明显

### ISSUE THREAD

**Issue by okliuxing** [fisheva/Eva-Theme#106]
主题已经升级到最新版。

在 git 更改视图下，新增的代码行是绿色背景的，注释类的文字是灰色的。

注释比较长的情况下，在绿色背景下很难看清楚，特别是在深色主题下面。

### Screenshot

<img width="461" alt="Snipaste_2023-12-14_09-54-59" src="https://github.com/fisheva/Eva-Theme/assets/122586699/21fcd140-0de8-4884-aa37-32eb84ea5494">

<img width="446" alt="Snipaste_2023-12-14_09-54-32" src="https://github.com/fisheva/Eva-Theme/assets/122586699/e22478ce-e84a-4b37-921f-8f38155e76cf">

### Code Snippet

比如：javascript、python。。。

## Supplement

> eva 是那个动漫eva吗，感觉配色好有动漫eva的风格

**Comment by fisheva** [comment]
@okliuxing 请升级Eva Theme到2.4.2，给Diff界面重新配色了下，提高了新增注释在该视图下的可见性。要兼顾美观和新增的提示作用，花了很长时间调试新的绿色背景，可能依旧不是很清晰，但好在这不是一个日常看代码的界面，目前的清晰度应该满足代码对比的使用需求了。
![WX20231217-135845@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/21de3153-d208-4c21-8162-d50985d3db71)
![WX20231217-231853](https://github.com/fisheva/Eva-Theme/assets/17448419/5f7f9a29-3460-44be-9bd9-1ace67de69e2)

是动画电影《Wall·E》(中文名《机器人总动员》)里的 eva

**Comment by okliuxing** [comment]
@fisheva 感谢回复！已更新到最新版本，比之前清晰一点了，这个 issue 可以关闭了。

> 好吧 我还以为是动漫eva 配色真的好康

![image](https://github.com/fisheva/Eva-Theme/assets/122586699/b697447d-bd70-4c9f-ab35-0e3e3b72cecb)
