### ISSUE TITLE
A little display error in CPP

### ISSUE THREAD

**Issue by ShanruChuan** [fisheva/Eva-Theme#107]
### Code Snippet

```cpp
int n_int = INT_MAX;
sizeof(int); // first
sizeof n_int; //second

```

## Supplement
sizeof两种用法颜色不同（eva-dark)。sizeof(int)；中“sizeof"呈现蓝色，与函数名的颜色相同。sizeof  n_int;中”sizeof"的颜色为白色，与变量名的颜色相同。sizeof在Cpp中是关键字，不是函数。其实无论是何种颜色，sizeof两种用法颜色统一即可。

**Comment by fisheva** [comment]
主题是根据字符的scope值为字符添加颜色的，字符的scope值由VSCode给定。您可以通过按Ctrl+Shift+P（Windows）或Cmd+Shift+P（Mac）并选择Inspect Editor Tokens and Scopes来检查它们。
![_20231215141429](https://github.com/fisheva/Eva-Theme/assets/17448419/c194eb86-0f84-4452-aca9-30b0a568c7ee)
![_20231215141443](https://github.com/fisheva/Eva-Theme/assets/17448419/4cef83d9-180c-4a31-8f3b-abf57180770e)

这里第二种写法的 sizeof 是变量颜色是由于VSCode对C++的支持不够深，字符的scope值给予的不够详细导致的，如果要强行颜色一致，只有把第一种颜色改成 变量颜色，但我觉得那样不好。
