### ISSUE TITLE
Textmate colorization for `record` keyword in `csharp` missing

### ISSUE THREAD

**Issue by sharpchen** [fisheva/Eva-Theme#108]
### Screenshot

![image](https://github.com/fisheva/Eva-Theme/assets/77432836/2cee9c3b-16cb-46a2-9544-c154a666413b)

### Code Snippet

```cs
record class Person(int Age, string Name);
```

**Comment by fisheva** [comment]
Fixed in 2.4.6.
![WX20231219-221351@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/5d2eb927-181e-4c61-ade7-236e826f257d)
