### ISSUE TITLE
Textmate colorization for `new` expression in `csharp` keyword incorrect

### ISSUE THREAD

**Issue by sharpchen** [fisheva/Eva-Theme#109]
target-typed `new` should be treated as regular keyword

### Screenshot
- Eva Dark
![image](https://github.com/fisheva/Eva-Theme/assets/77432836/969ada04-9721-4696-b96d-b2102764a368)

- Dark plus
![image](https://github.com/fisheva/Eva-Theme/assets/77432836/4fd45dbf-884c-4815-9720-6046739b4eb0)

### Code Snippet

```cs
Person p = new();
Person p = new Person();
int[] arr = new[] { 1, 2, 3 };
if (true) throw new Exception();
```

**Comment by sharpchen** [comment]
@fisheva Shall I include all colorization issue for csharp in one issue or separate them? I got some similar issue, may be annoying.

**Comment by fisheva** [comment]
It is best to put similar issues in the same issue, but for already opened issues, just put them there. It's okay.

**Comment by sharpchen** [comment]
Ok, thank you. I just found so many issues of textmate rules for csharp, I think I'd better learn something about textmate rules, and maybe make a PR someday?

**Comment by fisheva** [comment]
Of course, you can! I am a front-end programmer and I don't write C# in my daily work. I am looking forward to your PR.

**Comment by sharpchen** [comment]
I wonder how should I test my changes in my machine? Build `visx` in local and install it?

**Comment by fisheva** [comment]
There are two methods for testing:

1）Find the installation folder of the VSCode plugin, locate the Eva Theme, directly edit the theme file in the Themes folder, and then restart VSCode to see the changes take effect.
2)  Add the following text to the VSCode settings.json. 

```json
    "editor.tokenColorCustomizations": {
        //effect Eva Dark Italic Bold only
        "[Eva Dark Italic Bold]": {
            "textMateRules": [
                {
                    "scope": "source.cs keyword.operator.expression",
                    "settings": {
                        "foreground": "#A78CFA",
                        "fontStyle": "italic bold"
                    },
                },
            ],
        },
        //effect all themes
        "textMateRules": [
            {
                "scope": "entity.name.type.parameter",
                "settings": {
                    "foreground": "#FF6AB3",
                    "fontStyle": ""
                },
            },
        ],
}
```

Method 2nd doesn't need to restart VSCode, and the color modifications will override the first method.

**Comment by fisheva** [comment]
I have already fixed the C# syntax highlighting errors you mentioned today. Please upgrade Eva Theme to 2.4.6.
 
![WX20231219-221351@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/0a9629e3-15b9-4c15-b9dc-97e7651388f2)

I am going to bed now, see you.

**Comment by sharpchen** [comment]
Actually, didn't fixed somehow. I will PR my changes tomorrow, includes issues I raise today.
