### ISSUE TITLE
TypeScript enum 类型未正确高亮

### ISSUE THREAD

**Issue by duduluu** [fisheva/Eva-Theme#11]
```typescript
/**
 * Team
 */
export enum Team {
  /**
   * 天辉
   */
  Good = 'Good',
  /**
   * 夜魇
   */
  Bad = 'Bad',
}
```

![default](https://user-images.githubusercontent.com/10762097/42889489-2c03bf1e-8add-11e8-86c2-9d77d6b04d4f.PNG)

**Comment by fisheva** [comment]
修复了, 插件版本号没变, 还是0.3.8, 您看下可以更新吗?

**Comment by duduluu** [comment]
没有自动更新

**Comment by fisheva** [comment]
额, 我以为只要文件有改变, 所有用户就能看到插件需要更新了。本来觉得这么小的改动, 不值得加个版本号。

**Comment by duduluu** [comment]
![default](https://user-images.githubusercontent.com/10762097/42929643-3e9a6be2-8b6d-11e8-831b-fd3f5bd15670.png)
emmmmmm……enum是高亮了，但enum名还是没高亮……😂

**Comment by fisheva** [comment]
您期望的enum名是不是像声明Interface、Class时一样粉红并加粗?
<img width="315" alt="1" src="https://user-images.githubusercontent.com/17448419/42931973-a70f5c9a-8b73-11e8-9355-085f0c01e327.png">
因为我觉得相比Interface、Class,  enum的结构和用法更像Object, 对象名是黑色, 所以给enum名定的也是黑色。
