### ISSUE TITLE
Terminal is black?

### ISSUE THREAD

**Issue by g0dzcsgo** [fisheva/Eva-Theme#115]
### Screenshot

![image](https://github.com/fisheva/Eva-Theme/assets/45868344/25d6c759-6324-45f5-8322-ead1bb8e2528)

### Code Snippet

```
No Error
```

## Notes

Well, dont you see? it's black here why not make it transparent so it fits with the theme? What the fuck is this inconsistency

**Comment by fisheva** [comment]
I didn't make this change. It shows as the following on my computer. I guess it's some of your other VSCode extensions that changed the background.
<img width="1195" alt="QQ20240120-115015@2x" src="https://github.com/fisheva/Eva-Theme/assets/17448419/8934f2aa-6d0f-4995-bc02-eb3465654523">
