### ISSUE TITLE
Better colors for LUA syntax

### ISSUE THREAD

**Issue by g0dzcsgo** [fisheva/Eva-Theme#116]
When coding in lua I am missing some nice color for the "local" declaration it's just plain white same as the text.

Lemme show you what I mean:
![image](https://github.com/fisheva/Eva-Theme/assets/45868344/eb5df89d-94d2-4169-b40e-fe3a3953c3bf)

**Comment by fisheva** [comment]
Sorry for late reply. Supported Lua in 2.5.6.
