### ISSUE TITLE
期望增加更多textMate token 高亮配色的支持

### ISSUE THREAD

**Issue by BigMadDonkey** [fisheva/Eva-Theme#117]
Eva Dark的配色真的很舒服，不过经常遇到某些token的scope没有适配默认配色的情况。
例如
glsl:

<img width="772" alt="image" src="https://github.com/fisheva/Eva-Theme/assets/48643115/498c80da-6184-4ff8-ab91-60391de487e3">

这种，类型都没有设置默认的高亮。我觉得是不是可以给storage.xxx的scope提供一些默认的配色支持（或者再多一点通用的scope的配色支持）？

**Comment by fisheva** [comment]
请问这是什么编程语言，文件类型是什么？最好提供一段代码。

**Comment by BigMadDonkey** [comment]
语言为GLSL
我贴一段吧：
```GLSL
precision mediump float;

// uniform vec2 iResolution;
// uniform float iTime;
// uniform vec4 iMouse;

float plot(vec2 st, float pct) {
        return 1.0 - smoothstep(0.0, 0.02, abs(st.y - pct));
}

void main() {
    vec2 st = gl_FragCoord.xy / iResolution.xy;
    vec3 color = vec3(0.0, 1.0, 0.0);

    vec2 center = vec2(0.5);
    vec2 pos = st - center;

    float r = length(pos) * 3.0;
    float a = atan(pos.x, pos.y);
    a += iTime; 
    a *= 4.0;

    float f = cos(a);

    color += vec3(smoothstep(f, f + 0.1, r));

    gl_FragColor = vec4(color, 1.0);
}
```

语法解析我是用了WebGL GLSL Editor的插件 https://github.com/racz16/WebGL-GLSL-Editor

其实我是感觉主题配色按照语言一个个做支持有点坐牢，是不是VSCode的Color Theme有一些比较默认的token scope，我觉得对那些通用的scope设置统一配色是不是就好了

**Comment by fisheva** [comment]
同一作用的关键字，VSCode的token scope不同语言就是会有些许差异

**Comment by BigMadDonkey** [comment]
https://learnopengl.com/Getting-started/Shaders
请参考这个吧

**Comment by fisheva** [comment]
安装WebGL GLSL Editor插件，再把上面教程里的示例代码大部分粘到.frag文件里看了下，发现能新增的着色优化只有一句`storage.type.glsl`，请更新Eva Theme查看。

可以看出这个语法解析器还有很多待优化的地方，比如
- 无法识别#号注释，无法识别字符串;
- 逗号, 冒号: 点号. 方括号[] 感叹号! 等全都归入的是运算符;
- class, public, private, NULL 等一些关键字归类不对;

如果您希望这些字符的显示得到改善，得给WebGL GLSL Editor插件提issue。我日常没有用到GLSL，未来如果您发现语法解析升级完善了，可以再提issue让我同步对该语言的支持。
