### ISSUE TITLE
`bool` type and `true` and `false` in C isn't colored properly

### ISSUE THREAD

**Issue by rababR1** [fisheva/Eva-Theme#119]
### Screenshot
![image](https://github.com/fisheva/Eva-Theme/assets/65360255/436b28e0-e0bc-4639-9179-80399c17e589)

### Code Snippet

```C
int main()
{
    int x = 9;
    int y = x > 0;
    printf("y = %d\n", y);
    y = x == 9;
    printf("y = %d\n", y);
    y = x < 0;
    printf("y = %d\n", y);
    bool z = true;
    printf("z = %d\n", z); // Displays z as 1
    z = false;
    printf("z = %d\n", z); // Displays z as 0
    // Comparing stuff with logical operators
    int a = 7, b = 9;
}
```
Programming Language is C

## Notes
Following settings are enabled:
![image](https://github.com/fisheva/Eva-Theme/assets/65360255/1ef7d4e9-f909-4569-b8af-377cec717802)
![image](https://github.com/fisheva/Eva-Theme/assets/65360255/e9db538d-9a59-494b-b3c7-a242f01df1c0)
If you disable C_Cpp:Enhanced Colorization, this is what it looks like:
![image](https://github.com/fisheva/Eva-Theme/assets/65360255/81a9ec14-b79d-40ae-9149-831b66942cf6)

I hope that more proper colorizations (if C_Cpp:Enhanced Colorization is _enabled_ though) will come in the near future.

Thanks.

Edit: This also happens with the NULL keyword too:

![image](https://github.com/fisheva/Eva-Theme/assets/65360255/4f6c34f1-8dde-48e0-ad6d-06fe94f7ce3c)
C_Cpp:Enhanced Colorization enabled....
![image](https://github.com/fisheva/Eva-Theme/assets/65360255/a9f5c9f2-4d7c-49f8-beda-b41bd12f3efb)
C_Cpp:Enhanced Colorization disabled....

Code snippet:
```C
#include <stdio.h>
#include <stdlib.h>
int main()
{
    int a = 10;
    int *ptr = &a;              // ptr is a pointer to the variable a
    printf("ptr = %i\n", *ptr); // Prints the ADDRESS of the variable
    // a NULL pointer
    int *ptr2 = NULL; // does not point to ANYTHING!
    // Dereferencing a pointer
    int count = 10, x;
    int *intPointer; // Making a pointer for 'count'
    intPointer = &count;
    x = *intPointer; // dereferencing the pointer, GETTING THE VALUE ITS POINTING TO, which is 10 (NOT THE ADDRESS OF count)
    printf("count= %i,x = %d\n", count, x);
```

**Comment by fisheva** [comment]
I can only guarantee the best experience of Eva Theme under the following settings now. The characters you mentioned are displayed correctly under the following settings.

```json
    "editor.semanticHighlighting.enabled": false,
    "C_Cpp.enhancedColorization": "disabled",
```

The incompatibility of the plugin with the option `'C_cpp. enhancedColor': 'enabled'` is due to the scope values added to some characters by the plugin. Modifying these values may cause users to display errors if they do not install this plugin or set the option `'C_cpp. enhancedColor': 'disabled'`which are contradictory to each other.

For the semantic highlighting issue, please refer to [issue 54](https://github.com/fisheva/Eva-Theme/issues/54).

**Comment by rababR1** [comment]
Okay. Seems like I need to manually edit those scopes. Also, I edited my comment showing proper syntax highlighting

**Comment by rababR1** [comment]
Did a clean install of VS Code. Same issue. The screenshots are from _Insiders._
https://github.com/fisheva/Eva-Theme/assets/65360255/334b80b0-d3a8-46b5-aae0-6fa807d551e0

**Comment by fisheva** [comment]
Sorry, I didn't understand the meaning you wanted to convey in your two replies above. From your screenshot, it can be seen that after setting ` "C_Cpp.enhancedColorization": "disabled"`, the highlighted color of `NULL` is correct. Do you have any further questions that I need to answer?

If you want to overwrite the style of Eva Theme locally when ` "C_Cpp.enhancedColorization": "enabled"`, you can add the following text in the settings.

```json
"editor.tokenColorCustomizations": {
        //effect Eva Dark only
        "[Eva Dark]": {
            "textMateRules": [
                {
                    "scope": "entity.name.function.preprocessor.cpp,",
                    "settings": {
                        "foreground": "#CF68E1",
                    },
                },
            ],
        },
        //effect all Themes
        "textMateRules": [
            {
                "scope": "entity.name.function.preprocessor.cpp",
                "settings": {
                    "foreground": "#CF68E1",
                },
            },
        ],
}
```

I found that `entity.name.function.preprocessor.cpp` statement was not originally included, so there was no issue with conflicting settings, I just updated a version(2.6.1) and added this statement by default. 

If you find some characters display errors in ` "C_Cpp.enhancedColorization": "enabled"` settings and their scope statements are already in Eva Theme default settings, you may need to locally overwrite its color by using the above method.

**Comment by fisheva** [comment]
On my computer, regardless of the settings, `bool` and `true` displays in C language are always correct.
![WX20240506-070543@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/047877ce-1983-4f23-91e1-5093470e6d5b)

Can you show me their scope values when displaying errors on your computer?

**Comment by rababR1** [comment]
I've highlighted some strikethroughs when I inspect the scope. My build is Insiders v1.9.1
https://github.com/fisheva/Eva-Theme/assets/65360255/f9e30c4e-9e22-4497-a37a-1a0ed9ef7c37

**Comment by fisheva** [comment]
It didn't show the 'bool' scope value in the video. Could you show me again? Thanks!

**Comment by fisheva** [comment]
I found `entity.name.function.preprocessor.cpp` and `entity.name.function.preprocessor.cpp` can't be used to highlight `NULL` and `false`, it effects many other characters. So I just deleted it in the lasted version(2.6.2).
![20240508103604](https://github.com/fisheva/Eva-Theme/assets/17448419/3d789cf1-7480-4e0b-ade1-047f7a09f324)

**Comment by rababR1** [comment]
Sorry for the late response: Here it is...

https://github.com/fisheva/Eva-Theme/assets/65360255/b23be3c2-9a21-4256-a85d-5f9ef5c68519
