### ISSUE TITLE
在vscode中，C/C++宏定义的颜色可以更改吗？

### ISSUE THREAD

**Issue by Jinying-Tang** [fisheva/Eva-Theme#121]
目前，在vsocde中，颜色主题Eva Dark，C/C++宏定义的颜色是白色的

**Comment by fisheva** [comment]
定义为变量颜色是因为宏可以指代的东西有多种，我想不出哪种颜色更合适了
![WX20240519-114847@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/3000051c-39cf-45e2-b6a4-69af86993735)

**Comment by fisheva** [comment]
如果您想自定义宏的样式，可以在VSCode的settings.json里添加以下设置

```json
"editor.tokenColorCustomizations": {
        "[Eva Dark Italic Bold]": {
            "textMateRules": [
                {
                    "scope": "meta.preprocessor.macro entity.name.function.preprocessor,",
                    "settings": {
                        "foreground": "#B0B7C3", //颜色自定义
                        "fontStyle": "italic bold" //样式有italic bold, 空着就是normal
                    },
                },
            ],
        },
}
```

**Comment by Jinying-Tang** [comment]
另外，可以给局部变量、静态变量、全局变量着不同的颜色吗？

**Comment by fisheva** [comment]
做不到。

所有主题插件都是基于字符的Scope值给字符分配颜色。同时按下Ctrl+Shift+P(Windows)或Command+Shift+P(Mac), 选择检查TM作用域, 您可以查看字符的Scope值。

而VSCode提供的字符Scope值不能保证一个变量在定义和各种地方被调用时的Scope值一致。以下图`LENGTH`为例
![企业微信截图_20240520115306](https://github.com/fisheva/Eva-Theme/assets/17448419/9c678d5b-0ed7-49fc-8426-5355f265b6b4)
![企业微信截图_20240520115331](https://github.com/fisheva/Eva-Theme/assets/17448419/7248d7a1-2eda-4c74-9572-435a59417f7a)

**Comment by fisheva** [comment]
上面说法好像不严谨，应该说VSCode给的Scope值也没法区分 局部变量、静态变量、全局变量。

**Comment by Jinying-Tang** [comment]
> ```json
> "editor.tokenColorCustomizations": {
>         "[Eva Dark]": {
>             "textMateRules": [
>                 {
>                     "scope": "meta.preprocessor.macro entity.name.function.preprocessor,",
>                     "settings": {
>                         "foreground": "#B0B7C3", //颜色自定义
>                         "fontStyle": "" //样式有italic bold, 空着就是normal
>                     },
>                 },
>             ],
>         },
> }
> ```

谢谢你的耐心解答，非常不错的主题

**Comment by Jinying-Tang** [comment]
> 上面说法好像不严谨，应该说VSCode给的Scope值也没法区分 局部变量、静态变量、全局变量。

谢谢你的耐心解答，非常不错的主题

**Comment by Jinying-Tang** [comment]
> 如果您想自定义宏的样式，可以在VSCode的settings.json里添加以下设置
> 
> 
> 
> ```json
> 
> "editor.tokenColorCustomizations": {
> 
>         "[Eva Dark]": {
> 
>             "textMateRules": [
> 
>                 {
> 
>                     "scope": "meta.preprocessor.macro entity.name.function.preprocessor,",
> 
>                     "settings": {
> 
>                         "foreground": "#B0B7C3", //颜色自定义
> 
>                         "fontStyle": "" //样式有italic bold, 空着就是normal
> 
>                     },
> 
>                 },
> 
>             ],
> 
>         },
> 
> }
> 
> ```

这样设置在定义的时候可以更改着色，但在引用的时候依旧是白色
