### ISSUE TITLE
Neovim Theme 🎉

### ISSUE THREAD

**Issue by WillKirkmanM** [fisheva/Eva-Theme#123]
hi, @fisheva, I am tinkering the neovim version(see: [Eva-Theme.nvim](https://github.com/sharpchen/Eva-Theme.nvim)), I wonder how to move it under the organization?

_Originally posted by @sharpchen in https://github.com/fisheva/Eva-Theme/issues/93#issuecomment-2116926316_

**Comment by fisheva** [comment]
Yes, I knew. We chated [here](https://github.com/fisheva/Eva-Theme/pull/122).

**Comment by WillKirkmanM** [comment]
Apologies for my lack of dilligence. Closing...!

**Comment by fisheva** [comment]
![企业微信截图_20240528190537](https://github.com/fisheva/Eva-Theme/assets/17448419/5d0d7a10-f557-4c75-8e94-85c24c38e02d)
