### ISSUE TITLE
2.6.3版本C/C++宏的颜色为函数蓝，不是变量白

### ISSUE THREAD

**Issue by Jin-Whu** [fisheva/Eva-Theme#124]
### Screenshot

![image](https://github.com/fisheva/Eva-Theme/assets/18453216/f9f4ffa1-d2c3-4ecc-ad72-46476aea7733)

### Code Snippet

```

```

**Comment by fisheva** [comment]
在我电脑上显示如图
![WX20240522-004630@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/f0cb69db-8e2c-48da-84ed-538cf7f2b851)

解决方式：请在设置里搜索enhancedColorization，禁用 C_Cpp: Enhanced Colorization 选项。
![WX20240522-005214@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/8869a637-a7a1-4cdb-9f44-bb7d989e1974)

如果不禁用C_Cpp: Enhanced Colorization 选项，而把你说的位置改为变量色，那会把应该显示成函数色的地方也变成变量色。
![WX20240522-005544@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/436fc9ad-2c43-480e-94fc-9e81549740b3)

**Comment by Jin-Whu** [comment]
C_Cpp: Enhanced Colorization禁用了的

**Comment by fisheva** [comment]
按下Ctrl+Shift+P(Windows)或Command+Shift+P(Mac), 选择检查TM作用域。查看 BUFFSIZE 的Scopes值，截图发下

**Comment by Jin-Whu** [comment]
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/b70115c0-479b-4a23-8b88-01fea631aee8)

**Comment by fisheva** [comment]
在VSCode的settings.json里添加以下设置，试下能不能把字体颜色样式改过来

    "editor.tokenColorCustomizations": {
        "[Eva Dark Bold]": {
            "textMateRules": [
                {
                    "scope": "entity.name.function.preprocessor.c,",
                    "settings": {
                        "foreground": "#B0B7C3",
                        "fontStyle": ""
                    },
                },
            ],
        },
    },

**Comment by Jin-Whu** [comment]
试过上述方法没有效果，目前回退到2.6.0版本显示正常

**Comment by fisheva** [comment]
你是一小个版本一小个版本回退的吗？试过2.6.2和2.6.1吗？

**Comment by Jin-Whu** [comment]
目前试了2.6.2，2.6.1，2.6.0，宏变量和宏函数都是显示为白色

**Comment by Jin-Whu** [comment]
宏变量和宏函数如果能分别显示不一样的颜色更好，目前更新到2.6.3，使用semantic token可以起到改变macro颜色的效果，但是宏变量和宏函数的颜色是一样的

![image](https://github.com/fisheva/Eva-Theme/assets/18453216/667837e8-76db-4796-9671-04cc9a05139f)

![image](https://github.com/fisheva/Eva-Theme/assets/18453216/9fbd8ab6-9b7c-4a7c-b0dd-c990eef64629)

**Comment by fisheva** [comment]
```json
"editor.semanticHighlighting.enabled": false,
"C_Cpp.enhancedColorization": "disabled"
```
在关闭上述二个选项的前提下，我的显示就是这样
![WX20240522-010039@2x](https://github.com/fisheva/Eva-Theme/assets/17448419/ee691566-e220-4d82-8f9a-aacb7e4a5a1c)

**Comment by Jin-Whu** [comment]
上述两个选项关闭后，仍不起作用
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/f95dd17b-1edb-438d-ba81-b19043c44111)
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/b0f346e2-3788-45de-9c4c-2e62166503d2)

**Comment by fisheva** [comment]
截图看下关闭后的 BUFFSIZE Scopes值，截全

**Comment by Jin-Whu** [comment]
关闭后，仍然会显示semantic token type，该区域显示比较大，textmate scope区域无法截图完整
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/ea4e2813-0dea-4c5b-a05b-6b973a0c322a)
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/c2933a07-5254-4a17-a3de-e8c39c881e38)
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/1765c1df-ebda-4307-bfa6-6fdca9c6fbbd)
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/6692332d-42e9-497c-9532-c5c9e70ea720)

**Comment by fisheva** [comment]
```json
"editor.semanticHighlighting.enabled": false,
"C_Cpp.enhancedColorization": "disabled"
```
在这二项都已经禁用的前提下，还有semantic token，我只能猜测您还有别的插件给这些字符加上了semantic token，影响了它们的显示。

关闭VSCode，找到你的VSCode插件文件夹，先把除Eva Theme的其它插件挪出来，启动VSCode，看显示效果（如果这一步就显示错误，跟我说）。
再关闭VSCode，挪一半插件回来，启动VSCode，看显示效果。
如此反复，如果某次挪回插件后，发现显示出错了，说明问题插件就在刚刚挪进去的那批。
最终找出问题插件。

**Comment by Jin-Whu** [comment]
确定了是clangd插件添加了semantic token，禁用clangd插件后，宏变量和宏函数分别显示为白色和蓝色

**Comment by Jin-Whu** [comment]
现在C/C++开发，clangd插件可以提供比微软的C/C++插件更好的语法解析功能，作者的主题能适配clangd插件吗？

**Comment by fisheva** [comment]
抱歉，我不懂C/C++，日常也使用不到。着色时只是找篇教程把所有示例代码复制放到VSCode里看Scopes值着色。

我建议您去搜下，或去clangd插件仓库issue问下是否有设置选项可以像 `"C_Cpp.enhancedColorization": "disabled"` 一样关闭掉该插件的semantic token。

适配clangd得靠日常使用者，在发现字符配色和样式不对时，尝试添加编写scopes规则将其修正，提pull request。这是个日积月累打补丁的过程。

**Comment by fisheva** [comment]
尝试添加编写scopes规则时，可以先在settings.json里像下面这样看效果

```json
  "editor.tokenColorCustomizations": {
      "[Eva Dark Bold]": {
          "textMateRules": [
              {
                  "scope": "entity.name.function.preprocessor.c,",
                  "settings": {
                      "foreground": "#B0B7C3",
                      "fontStyle": ""
                  },
              },
          ],
      },
  },
  ```

**Comment by Jin-Whu** [comment]
使用如图所示的设置，semantic token不起作用了
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/0926edf5-d0c9-463a-9d80-606dca818dd9)
![image](https://github.com/fisheva/Eva-Theme/assets/18453216/8abebb64-8dc8-4c93-9c42-0c2699ecd558)

**Comment by fisheva** [comment]
"[c]"有父级属性吗？还是直接写在settings.json下？

**Comment by Jin-Whu** [comment]
在settings.json里面使用editor.semanticHighlighting.enabled: false不起作用，必须在language下指定才起作用

**Comment by fisheva** [comment]
新知识get, 谢谢分享!
