### ISSUE TITLE
Weird new colors

### ISSUE THREAD

**Issue by g0dzcsgo** [fisheva/Eva-Theme#125]
Ok so just booted up vscode for the first time in a while, and noticed that now constant variable names are colored. Aswell as parameters are colored inside functions?

Examples:
![image](https://github.com/fisheva/Eva-Theme/assets/45868344/141a8615-7ad1-4345-b171-54f4d9e8759e)
![image](https://github.com/fisheva/Eva-Theme/assets/45868344/141a8615-7ad1-4345-b171-54f4d9e8759e)

Is this a visual studio code thing? I tried going back versions and it stayed the same. I don't rememember it being that color before

I know the parameter is a yellow color. But what I dont like is that the yellow color also continues showing when used inside of the function. Before it was white

**Comment by fisheva** [comment]
1. May I ask what programming language it is?
2. Can you provide a more complete code that includes the constants, functions, and parameters you mentioned, and indicate which characters you think are color incorrect?
3. Try to turn off semanticHighlighting then see if the character color matches your expectations?
![企业微信截图_20240611100358](https://github.com/fisheva/Eva-Theme/assets/17448419/ddc126a4-3eb1-4a24-a561-ec8e969ce43b)
