### ISSUE TITLE
在定义变量的时候，普通的变量类型和变量名之间的多余空格不会删除，但是指针类型的多余空格就会删除

### ISSUE THREAD

**Issue by Jinying-Tang** [fisheva/Eva-Theme#126]
### Screenshot

![image](https://github.com/fisheva/Eva-Theme/assets/131565469/0f85a454-3ad2-4330-9603-403c4efbb5dc)
请问这是主题的问题，还是c/c++扩展设置的问题？
### Code Snippet

```

```

**Comment by fisheva** [comment]
主题只能定义界面和代码字符的显色，涉及编辑操作，是其它插件导致吧？
