### ISSUE TITLE
请求将EvaTheme的Windows终端配色方案添加到Windows Terminal Themes网站

### ISSUE THREAD

**Issue by TomDan-GodsHand** [fisheva/Eva-Theme#127]
@fisheva   你好
我非常喜欢EvaTheme，它的配色方案非常舒适。为了让我的Windows Terminal也能体验到同样的效果，我基于EvaTheme的终端配色制作了一个自定义的配色方案。

配色方案详情：

颜色来源：配色方案的颜色直接来源于EvaTheme的终端配色。
修改：由于Windows Terminal不支持配色方案中的透明度，我从EvaThem.nvim中复制了选中时的背景色，以保持EvaTheme视觉体验的一致性和完整性。
请求：

我想询问是否可以将我制作的EvaTheme配色方案添加到[WindowsTerminalThemes](https://windowsterminalthemes.dev/)网站上，供其他人发现和使用。这个网站是发现和分享终端主题的优秀资源，我相信我的EvaTheme配色方案也会是一个很好的补充。

如果你不同意将我的配色方案加入网站，我也会尊重这个决定，并从我的个人仓库中删除它。

地址是[https://github.com/TomDan-GodsHand/Eva-themes](https://github.com/TomDan-GodsHand/Eva-themes)

代码:

```
        {
            "background": "#282C34",
            "black": "#000000",
            "blue": "#4283F5",
            "brightBlack": "#676E95",
            "brightBlue": "#6495EE",
            "brightCyan": "#56B7C3",
            "brightGreen": "#4EC150",
            "brightPurple": "#FF6AB3",
            "brightRed": "#F14C4C",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FF8A4C",
            "cursorColor": "#9DA5B3",
            "cyan": "#56B7C3",
            "foreground": "#B0B7C3",
            "green": "#4EC150",
            "name": "Eva Dark",
            "purple": "#CF68E1",
            "red": "#E51400",
            "selectionBackground": "#394E75",
            "white": "#8A97C3",
            "yellow": "#E4BF7F"
        },
        {
            "background": "#EBEEF5",
            "black": "#FAFAFA",
            "blue": "#4480F4",
            "brightBlack": "#AAADB4",
            "brightBlue": "#4D91F8",
            "brightCyan": "#00BEC4",
            "brightGreen": "#44C145",
            "brightPurple": "#EF8ED8",
            "brightRed": "#F14C4C",
            "brightWhite": "#888888",
            "brightYellow": "#FF6D12",
            "cursorColor": "#FFFFFF",
            "cyan": "#00BEC4",
            "foreground": "#5D5D5F",
            "green": "#44C145",
            "name": "Eva Light",
            "purple": "#C838C6",
            "red": "#EC0000",
            "selectionBackground": "#B0CBF7",
            "white": "#000000",
            "yellow": "#F0AA0B"
        },
```

截图：
![mmexport1718781697928.png](https://github.com/fisheva/Eva-Theme/assets/87116918/c3b2683d-83a0-49b3-951e-799eea67fbab)

![mmexport1718781693066.png](https://github.com/fisheva/Eva-Theme/assets/87116918/aacda3c4-d8bb-4e0d-b078-b03cd2dd3df6)

感谢您考虑我的请求！我希望EvaTheme社区和Windows Terminal Themes的用户们能发现并使用这个配色方案，享受它带来的美好体验。

**Comment by fisheva** [comment]
Awesome! 感谢您拓展了Eva Theme的影响力！请问在README里这里的点击 Terminal 跳转链接是放 https://github.com/TomDan-GodsHand/Eva-themes 吗？
![image](https://github.com/fisheva/Eva-Theme/assets/17448419/038980ec-53c4-4519-8e62-06905078efd4)

**Comment by TomDan-GodsHand** [comment]
你好，是的，但是有一个问题，软件的名字是叫做Windows Terminal ，而不是Terminal 。
非常感谢你的认可，希望EvaTheme 能发展的更好！

**Comment by fisheva** [comment]
OK, 已更新附上您的链接~🎉 
![企业微信截图_20240620094750](https://github.com/fisheva/Eva-Theme/assets/17448419/298b409b-83a2-47ab-a83d-b14f45f7f6ec)

**Comment by TomDan-GodsHand** [comment]
非常感谢

**Comment by sharpchen** [comment]
@fisheva I think it's better to have a specification for *[Console Colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors)* so one can port the color theme consistently for other terminal emulators.
