### ISSUE TITLE
Your theme is really good. But I think it lacks the highlighting of the variables declaration, such as const or let in JS or $ in PHP

### ISSUE THREAD

**Issue by TheDanieLSh** [fisheva/Eva-Theme#128]

**Comment by fisheva** [comment]
Could you provide some code and screenshots to describe your request in detail?

**Comment by TheDanieLSh** [comment]
> Could you provide some code and screenshots to describe your issue in detail?

Sure. Here's examples with your theme and some other theme

![image](https://github.com/user-attachments/assets/c3f4f68f-29e8-4b3a-9cca-eb3a2c9670b6)
![image](https://github.com/user-attachments/assets/44468e18-62ea-4129-8422-55b7269b9df1)
![image](https://github.com/user-attachments/assets/ffc71c6f-4d7c-4077-96f8-d275ab534240)
![image](https://github.com/user-attachments/assets/0a96098c-795b-45e5-afa9-a5b65c31c37e)

**Comment by fisheva** [comment]
It should be some other plugin affected your JS `let` `var` color.
<img width="176" alt="WeCom20240902-144359@2x" src="https://github.com/user-attachments/assets/ca89be0a-d3e0-4997-b071-8d1b12d81e0a">

<img width="741" alt="WeCom20240902-144253@2x" src="https://github.com/user-attachments/assets/c14a0716-f941-4658-a4d5-9750585c6a2a">

$ in PHP always used with variables, so I set them the same color for good looking.

**Comment by TheDanieLSh** [comment]
Hmm okay. Strange that it doesn't affect other themes. But thank you, anyway!

**Comment by rababR1** [comment]
Also, include syntax highlighting for SQL!
