### ISSUE TITLE
Why is `True` in Python not colored properly?

### ISSUE THREAD

**Issue by rababR1** [fisheva/Eva-Theme#129]
### Screenshot
![image](https://github.com/user-attachments/assets/93c6d899-68f8-417f-a82c-0215d0e8585c)
Should be this when semantic highlighting is enabled, I had to manually edit it in the `settings.json` file:
![image](https://github.com/user-attachments/assets/3bb71547-4783-4b59-8fb9-2a6fb01fdd1c)

### Code Snippet

```py
def validateInteger(prompt):
    while True:
        try:
            return int(input(prompt))
        except ValueError:
            print("That's not an integer!\n")
            continue
```
The language is Python
## Notes
This is with semantic highlighting enabled.

**Comment by fisheva** [comment]
It displays correct in my computer, whether I enabled semantic highlighting.
<img width="1676" alt="WeCom20240905-154343@2x" src="https://github.com/user-attachments/assets/f829d48d-3a38-480e-8d50-028ade271c80">

It may some of your other plugin add the semantic syntax rule, recognised the `True` as `variable.other.constant`, I can't style this rule as boolean. And Eve Theme doesn't support semantic highlighting currently.
