### ISSUE TITLE
Python 函数参数列表里变量高亮颜色和本身变量高亮颜色不同

### ISSUE THREAD

**Issue by bryceyang** [fisheva/Eva-Theme#13]
如图，函数参数列表里变量高亮颜色和函数高亮颜色变得一样，而变量本来的高亮颜色应该为灰色。
<img width="600" alt="screenshot 2018-09-17 00 20 22" src="https://user-images.githubusercontent.com/9302617/45598498-7da45e80-ba0f-11e8-8f89-571b733834c4.png">
在另一个主题里，对应高亮如下：
<img width="618" alt="screenshot 2018-09-17 00 19 30" src="https://user-images.githubusercontent.com/9302617/45598503-87c65d00-ba0f-11e8-811d-e03d7aac00ce.png">

希望作者能考虑下将函数参数列表里的变量高亮颜色和原本高亮颜色保持一致，比如都保持灰色。

**Comment by fisheva** [comment]
谢谢您帮我又找出了一个没打上补丁的位置, 请更新插件查看最新效果。

我照着您的代码打了一遍:
![image](https://user-images.githubusercontent.com/17448419/45610688-6e64f580-ba8f-11e8-998a-743df935f903.png)
修正后:
![image](https://user-images.githubusercontent.com/17448419/45612353-53957f80-ba95-11e8-9110-5f3e532023e9.png)

顺便说下, VSCode的主题插件是根据字符的Scope值给每个字符定义颜色的, 而每个字符的Scope值是由VSCode算法分配的。这个算法的分配结果, 目前来说 很乱, 同一字符在不同语言/代码语境下, Scope值常常不同。所以VSCode的主题制作是个长期打补丁的过程。如果您未来发现有什么位置颜色不对劲, 欢迎继续提issue, 截图+复制一份代码就更好了(逃 :D
