### ISSUE TITLE
color of variables in sass (Eva Light Bold)

### ISSUE THREAD

**Issue by noctildon** [fisheva/Eva-Theme#15]
![sass](https://user-images.githubusercontent.com/42067562/47651038-0ab90680-dbbd-11e8-87d2-00c6b188c2c6.png)

As shown in picture, the color of sass property(ex. width) is so similar to the color of sass variable(ex. $length)
Is there any way to make the difference more noticeable?

```sass
// code in the picture
@mixin block($length: 50px, $boxcolor: green, $color: green)
  width: $length
  height: $length
  background-color: $boxcolor
  border: solid 2px $color
```

**Comment by fisheva** [comment]
Very thank you for your detailed issue!

This is the appearance of this code in the latest version.

<img width="625" alt="qq20181031-162930 2x" src="https://user-images.githubusercontent.com/17448419/47775628-23472f00-dd2b-11e8-94ae-64b18b778f36.png">

Any new issue is welcome! Thanks!

**Comment by noctildon** [comment]
Excellent! Thanks for bug fixing. This color theme is really amazing!
