### ISSUE TITLE
空格的颜色过深, 建议调浅一些

### ISSUE THREAD

**Issue by zsedcbm** [fisheva/Eva-Theme#18]
![image](https://user-images.githubusercontent.com/5986396/50195176-f4d3f080-0378-11e9-9438-f721771b9763.png)
空格多的时候,感觉颜色深了一些, 比较干扰视线, 相比较下自带样式的要舒服很多.

**Comment by fisheva** [comment]
对照自带样式的深度, 降低了些, 请更新下插件, 谢谢提议!

**Comment by fisheva** [comment]
![image](https://user-images.githubusercontent.com/17448419/50221295-a271ee80-03cf-11e9-98ea-57c34dc968b5.png)
