### ISSUE TITLE
GraphQL input keyword isn't styled

### ISSUE THREAD

**Issue by Aidurber** [fisheva/Eva-Theme#19]
Hello!

Firstly, thanks for the awesome theme!

There is a minor issue with GraphQL files, the `input` keyword isn't coloured as well as user defined types i.e. `CreateUserInput` and `AuthResponse`:

**With Eva**
<img width="574" alt="screenshot 2018-12-23 13 27 59" src="https://user-images.githubusercontent.com/5732291/50384059-e8bc9b80-06b6-11e9-9a8b-6bbe325b238d.png">

I was unsure whether it was the [GraphQL for VS Code Extension](https://github.com/kumarharsh/graphql-for-vscode) or Eva Theme, so I disabled the GraphQL extension and the problem still exists. 

Here is what it looks like on the default VS Code Dark+ theme:
**With VS Code Dark+**
<img width="1026" alt="screenshot 2018-12-23 13 31 58" src="https://user-images.githubusercontent.com/5732291/50384077-3fc27080-06b7-11e9-9796-4626e0c5cc07.png">

**Comment by fisheva** [comment]
Thanks for your detail issue! I have fixed it in the new version. 
Any new issue is welcome! Merry Christmas!
![image](https://user-images.githubusercontent.com/17448419/50423555-02fea100-0892-11e9-8f9c-639bfae3fbe0.png)
