### ISSUE TITLE
不知道为什么我同字符选中不会高亮

### ISSUE THREAD

**Issue by yanjingenious** [fisheva/Eva-Theme#2]
并不会高亮相同的字符，开始也为是我的vscode的问题，最会换别的主题没这个问题。
![qq20171204-200251](https://user-images.githubusercontent.com/19990773/33552021-f9306f28-d8b8-11e7-9ec1-e9623530679e.png)

**Comment by yanjingenious** [comment]
好吧，不知道什么鬼，又有效果了，日常抽风吗

**Comment by fisheva** [comment]
所以是自动恢复了吗?

**Comment by yanjingenious** [comment]
@fisheva 并没有回复，当时我以为恢复了，结果是切到了别的主题，忘记了，还也为又好了，我使用了几个其他得主题又的和你的一样也是高亮不了，有的可以

**Comment by fisheva** [comment]
@yanjingenious 可以把你说的那段代码文件发我一份吗? 我的邮箱是fishyu_eva@qq.com
主题只是外观, 而这些功能是VSCode软件内核, 按理二者是互不影响的, 如果真有这样的BUG, 说实话都不知道该怎么跟VSCode提issue.
我在编写这个主题的时候, 就给在VSCode团队工作的一个知友发过邮件, 希望对VSCode编写主题方面有更细致的了解, 邮件里提了很多具体问题, 最终都没有收到答复.

**Comment by yanjingenious** [comment]
@fisheva 不知道你自己那里有没有这个问题，我是整个项目都有这个问题，有的可以高亮有的就高亮不了
![19 52](https://user-images.githubusercontent.com/19990773/33883375-7e325b8c-df76-11e7-97d0-17f1e194397e.gif)

**Comment by fisheva** [comment]
@yanjingenious 从你发的这张GIF, 我看到的是:
如果选中的是 框架中的 函数名 或 变量, 那么其它相同的 函数名 或 变量 就会被高亮;
如果选中的是Javascript语言关键字 如import, from, imgSrc (回头重新看了下您发的第一次issue那张图) ,那其它相同的关键字不会高亮;

整个功能没问题啊, Javascript的语言关键字 既不能修改其内部函数, 同一个关键字用在不同地方 也不互相影响, 所以并不需要高亮啊, 如果你需要找到某个关键字所有地方, 请用 查询搜索 cmd(ctrl) + F.

为什么选中非Javascript语言关键字的 函数名 和 变量, 会高亮其它位置? 因为它们是同一个东西, 相互影响, 可被修改, 而且修改其中一个, 其它的全部跟着一起变.

所以这个问题不是软件出了BUG, 是您对这个功能的理解有偏差, 不知这个解释您满意不.

**Comment by fisheva** [comment]
@yanjingenious 您好! 很抱歉之前没发现您说的这个问题, 最近又有用户提出, 然后在我增加更多语言支持时, 发现确实在某些语言中存在这个问题。查找后, 发现问题出在 VSCode二个API "editor.selectionHighlightBackground" 和 "editor.wordHighlightBackground"区分不严, 在某些本该由"editor.wordHighlightBackground"起作用的地方, 是"editor.selectionHighlightBackground" (之前被我设置成了透明)在生效, 现在在0.2.5版本将错就错的依着VSCode修改了"editor.selectionHighlightBackground"的颜色与"editor.wordHighlightBackground"相同, 未来有机会我会向VSCode提交这个issue。
