### ISSUE TITLE
C/C++ 基本变量类型高亮错误

### ISSUE THREAD

**Issue by yjl9903** [fisheva/Eva-Theme#21]
Eva light 主题在 vscode 1.33.0 版本更新后，C/C++ 基本变量类型高亮显示错误。
在之前的版本中，变量类型的颜色应该是 `#EF8ED8`，结构体和类的关键字 `struct` 和 `class` 的颜色对应为 `#7C4DFF`。

**Comment by fisheva** [comment]
我看到您的邮件并给您回复了。不过昨天没注意变量类型颜色, 现在也改过来了, 请将Eva Theme更新到0.7.5版本。修正了 变量类型颜色和结构体关键字Struct颜色。类关键字class貌似没有出错? 如果您有错误示例代码, 请提供下截图和代码Copy。
![image](https://user-images.githubusercontent.com/17448419/55677766-54520e00-5920-11e9-93de-f11d2bc6e0c0.png)
