### ISSUE TITLE
js导入模块语句不显示

### ISSUE THREAD

**Issue by Arichy** [fisheva/Eva-Theme#22]
js导入模块的语句不显示
1. commonjs语法
![9C0C5926-C766-4B25-862B-0F355C4226DA](https://user-images.githubusercontent.com/29599723/55683462-bdfb0800-5972-11e9-88a4-dd3283e4dfe4.png)
其中变量fs不显示
2. ES6语法
这里有三条语句，但三条全都看不见了
![BF3F1EA8-EFAC-44EE-8EBC-66E68FCC5380](https://user-images.githubusercontent.com/29599723/55683476-d834e600-5972-11e9-96be-a807911872af.png)
加上注释才能看见
![2E312748-0446-4950-B90E-22B6F26D7E51](https://user-images.githubusercontent.com/29599723/55683490-f1d62d80-5972-11e9-8dd4-3180333d8f84.png)
或者使用过该模块之后才能看见
![BC7660CF-D4E4-4AAF-8F13-12EB1ABBCA43](https://user-images.githubusercontent.com/29599723/55683497-01557680-5973-11e9-9434-1f73b0cfe86f.png)

**Comment by fisheva** [comment]
VSCode 1.3.3 把下面这个API参数计算方式变了, 之前颜色后面填00是无透明度实心, 现在得填成FF
"editorUnnecessaryCode.opacity": #FFFFFF00 → #000000FF;
已修正, 请将Eva Theme更新至0.7.6版本。
