### ISSUE TITLE
速览问题弹窗颜色不协调

### ISSUE THREAD

**Issue by wangwg1994** [fisheva/Eva-Theme#24]
![image](https://user-images.githubusercontent.com/24909046/59480258-7ae97380-8e92-11e9-8990-3e6e05f43e15.png)

**Comment by fisheva** [comment]
您可以复制份代码给我吗？我好复现问题，谢谢！

**Comment by wangwg1994** [comment]
`<div v-show="isTypeShow" class="type-main">
          <Row type="flex" justify="start" v-for="(type4, index4) in typeList" :key="index4">
            <Col span="6" v-for="(type, index) in type4" :key="index">
              <div
                class="type-box"
                @click="onTypeBoxClick(type)"
                :class="{ activeBorder: activeType ? activeType.id === type.id : false}"
              >
                <div class="type-pic-box">
                  <img :src="type.image_url" alt class="type-pic">
                </div>
                <div class="type-title">{{type.name}}</div>
              </div>
            </Col>
          </Row>
        </div>`
eslint提示报错如下，点速览问题就出现上图弹窗了
![image](https://user-images.githubusercontent.com/24909046/59481067-73779980-8e95-11e9-968a-f750e2271c47.png)

**Comment by fisheva** [comment]
谢谢帮忙找BUG! 问题已修复, 请升级插件至0.7.7版本。
VSCode官方文档界面API许多没有图片, 光看文字不知道具体指哪里, 像这处BUG, 遇到了, 通过调试颜色才慢慢对应上。
