### ISSUE TITLE
the font on status bar is hard to read in running state

### ISSUE THREAD

**Issue by YinlinHu** [fisheva/Eva-Theme#25]
Thanks for this fantastic color scheme. One minor problem, the font on the status bar is OK, but when in running state, the background of the status bar will turn to RED, making the font on it hard to read.

**Comment by fisheva** [comment]
Sorry for coming late. I guess your "running state" means debugging. So I brightened the color of "statusBar.debuggingForeground" in the new version. Please update Eve Theme to 0.7.8 , try it.

I have tried pure white, but it feels too glaring.  It's difficult to find a balance between "clearly visible" and "not glaring". If you feel that the color I set is not bright enough for you, you can set it yourself below:
```json
{
  "workbench.colorCustomizations": {
      "statusBar.debuggingForeground": "#DCDFE5",
  }
}
```
![image](https://user-images.githubusercontent.com/17448419/63228228-b30a8b00-c222-11e9-9c23-07dd66588eb5.png)

**Comment by YinlinHu** [comment]
That's great, I think it is much better now.
