### ISSUE TITLE
如何更改函数参数颜色一致

### ISSUE THREAD

**Issue by rayle2** [fisheva/Eva-Theme#27]
看您简介，应该是国人，我就先用中文写了。
首先非常喜欢这个主题，不过我有一个问题想请教，函数的参数如何设置成一样的颜色？期待您的解答。
Hello, I am a Chinese developer, the following is from Google Translate
First of all, I really like this theme, but I have a question I would like to ask, how to set the parameters of the function to the same color? Looking forward to your answer.
![QQ截图20190903103326](https://user-images.githubusercontent.com/17264314/64140557-5cfb3180-ce37-11e9-9377-ab1bded2c4f9.png)

**Comment by fisheva** [comment]
这也是我一直想做到的效果, 无奈由于VSCode对函数里的参数 与 普通变量的Scope Value分配上没有做区分, 所以目前做不出来这种效果。
按下"Ctrl+Shift+P"(Window) 或 "Cmd+Shift+P"(Mac) 选中 "Inspect TM Scopes" 可以查看所有字符的Scope值。
目前VSCode的字符Scope值分配规则有许多混乱的地方, 不知道开发团队什么时候能重视这块, 修复这些bug。
这是我在知乎上的一条回答 https://www.zhihu.com/question/267039478/answer/381516956

**Comment by rayle2** [comment]
> 这也是我一直想做到的效果, 无奈由于VSCode对函数里的 参数 和 普通变量 的Scope Value分配上没有做区分, 所以目前做不出来这种效果。
> 按下"Ctrl+Shift+P"(Window) 或 "Cmd+Shift+P"(Mac) 选中 "Inspect TM Scopes" 可以查看所有字符的Scope值。
> 目前VSCode的字符Scope值分配规则有许多混乱的地方, 不知道开发团队什么时候能重视这块, 修复这些bug。
> 这是我在知乎上的一条回答 https://www.zhihu.com/question/267039478/answer/381516956

**Comment by rayle2** [comment]
谢谢。了解了。
那就一直用您这个主题，等官方更新了。
