### ISSUE TITLE
Light 主题下终端颜色有问题

### ISSUE THREAD

**Issue by Robotxm** [fisheva/Eva-Theme#28]
![image](https://user-images.githubusercontent.com/5405331/65518812-7b74ba00-df17-11e9-996c-c2d250c480a7.png)

VSCode 1.38.1
如图，终端里有些路径和关键字的颜色在 Light 主题下是白色的，这样就看不清了。

**Comment by fisheva** [comment]
抱歉来晚了! 请先将Eva Theme升级到<del>0.7.9</del>最新版本。
终端里的文字颜色设置对我而言也是个黑盒, 它不像代码编辑区可以随便拷份代码进行调试配色, 官方给的文档也很模糊
![image](https://user-images.githubusercontent.com/17448419/70531689-64e21480-1b90-11ea-8fe9-5b1981e8734e.png)

所以必须操作到那, 遇到了才知道各个API代表了哪些文字颜色。我是个前端新人, 终端用的还不多, 所以之前API名字叫什么, 我就给了个相应的颜色
![image](https://user-images.githubusercontent.com/17448419/70531696-6ca1b900-1b90-11ea-8873-36978b764354.png)

箭头所示位置原来填的是"#FFFFFF"白色, 从您给的图看, 确实白色是不能用了, 现在改成了灰色。如果可以, 往后您觉得终端哪里颜色不好的, 还请多多截图提交给我, 感谢!

**Comment by Robotxm** [comment]
非常感谢修复了这个，强迫症总算可以一本满足了

**Comment by fisheva** [comment]
您好，因为[issue#58](https://github.com/fisheva/Eva-Theme/issues/58)，我在1.6.3版本对Terminal的API颜色做了些改动。现在的设置是
```
//Eva Light
terminal.ansiWhite: #FFF
terminal.ansiBrightWhite: #AAADB4
```
如果您发现路径名又变成了纯白色，我再到下版本把这2个颜色对调试试。

你也可以在VSCode的setting.json里自测下：
    "workbench.colorCustomizations": {
        "terminal.ansiBrightWhite": "#AAADB4",
        "terminal.ansiWhite": "#fff",
}
修改上面2个的颜色，看是哪个API影响了您说的文件路径文字，再告知我，谢谢！

**Comment by Robotxm** [comment]
![image](https://user-images.githubusercontent.com/5405331/128322307-4aa26410-897a-47a4-938b-1f6788036449.png)
首先非常感谢作者还能跟进这个两年前的 issue。我这边测试了一下是灰色，看起来应该匹配到了 `terminal.ansiBrightWhite` 这项。

**Comment by fisheva** [comment]
能在Dark模式下，在同样位置再截个图给我吗？我想看下这个地方在Dark模式下的观感，再考虑怎么调。谢谢！

**Comment by Robotxm** [comment]
![image](https://user-images.githubusercontent.com/5405331/128329491-4e989d96-5edd-4a8d-8575-e1da7782cba5.png)
Dark 模式中路径和后面的提示信息感觉颜色区分不太开了。

**Comment by fisheva** [comment]
![Uploading 企业微信截图_20210805180051.png…]()
你觉得这2处文字的颜色是统一成一种好，还是像这样有区分度更好？

**Comment by Robotxm** [comment]
> ![企业微信截图_20210805180051](https://user-images.githubusercontent.com/17448419/128332093-e6ab7472-696d-4f46-83a5-14b5211b6acf.png)
> 
> 你觉得这2处文字的颜色是统一成一种好，还是像这样有区分度更好？

我个人的看法是类似 Light 那样有区分度会好一点。

**Comment by fisheva** [comment]
好的，下版本修改。

以后遇到Terminal里有文字看不清的情况，欢迎继续截图告知我~

**Comment by fisheva** [comment]
您好，我昨晚突然想到，能帮我在相同位置截下VSCode默认Dark和Light主题下的样子让我看看吗？
![128329491-4e989d96-5edd-4a8d-8575-e1da7782cba5](https://user-images.githubusercontent.com/17448419/128452662-90425c9a-2922-43a7-8d26-10674d1f135b.png)
具体原因是这样，最近这次修改Terminal的颜色，是因为[issue 58](https://github.com/fisheva/Eva-Theme/issues/58)让我知道原来`terminal.ansi...`这些API不仅控制Terminal里的文字颜色，还控制像 `ConsoleColor.Yellow`这样向控制台打印颜色的操作的输出结果。所以需要使`terminal.ansi...`这些API的颜色尽量符合它所描述的色系。然而在Light模式下`terminal.ansiBrightWhite`这个API就两难了，如果想它符合白色这个色系，那就会出现你最初截图文字看不清的情况。
![65518812-7b74ba00-df17-11e9-996c-c2d250c480a7](https://user-images.githubusercontent.com/17448419/128453329-165af991-7da0-424a-be54-0cbd6f6c13f9.png)
所以我的抉择是以文字能看清为优先，给了`terminal.ansiBrightWhite`灰色。我想看VSCode默认Dark和Light主题下相同位置的截图，也是想看官方的默认主题是怎么处理这个问题的。

**Comment by Robotxm** [comment]
![image](https://user-images.githubusercontent.com/5405331/128599251-41877490-a496-4ff3-916f-6deb0ae4e73e.png)
![image](https://user-images.githubusercontent.com/5405331/128599264-0eaa8547-45a3-408d-89be-4dd26e29dac9.png)

抱歉今天才看见 GitHub 的通知。默认的 Dark+ 和 Light+ 如图。
