### ISSUE TITLE
黑色主题的时候，状态栏太暗，看文字有点费劲

### ISSUE THREAD

**Issue by dylan-7** [fisheva/Eva-Theme#3]
编程的时候经常会看vscode状态栏，设置为黑色主题时，状态栏太暗，看字很费劲，可以使文字变明亮些或者背景色变得反差大些吗

![bar](https://user-images.githubusercontent.com/11660473/36015776-fd5571bc-0daa-11e8-9e26-e6d152b54d6b.png)

**Comment by fisheva** [comment]
已修改, 更新下最新版本0.1.4 看看.

**Comment by dylan-7** [comment]
@fisheva 完美！感谢制作了这款优秀的主题。
