### ISSUE TITLE
几个小意见

### ISSUE THREAD

**Issue by roy-tian** [fisheva/Eva-Theme#30]
写C/C++多些，对深色theme提几个小小的意见：
1. 80字符的ruler是亮蓝色，与背景略显违和；
2. 无法为CMakeLists.txt着色；
3. C++中未对 template和typename 着色（不知是不是有意为之）

总之楼主这套theme奶香奶香的，用起来很舒服很喜欢！

**Comment by fisheva** [comment]
谢谢支持~ :D

1,没懂这个意思, 可以上段代码吗?最好是截图+代码片段

后面2条需求get到了, CMake我还要去了解下。

**Comment by roy-tian** [comment]
![就是这根线](https://user-images.githubusercontent.com/37997454/66524961-812ceb00-eb26-11e9-8498-60b40b297e34.png)
就是这根线，个人觉得可以略微调淡一点。仅供参考:)

**Comment by fisheva** [comment]
issue开启二周后您关闭了, 隐隐感受到关闭那一刻您的失望。时隔这么久才fix, 对不起! 让您久等了。
请更新Eva Theme至<del>0.7.9</del>最新版本。

阅读下面回答的预备了解: 按下"Ctrl+Shift+P"(Window) 或 "Cmd+Shift+P"(Mac) 选中 "Inspect TM Scopes" 可以查看所有字符的Scope值。

回答您的问题:
1, 已调淡。
2, 阅读一篇[新手教程](https://medium.com/@sam.romano18/visual-studio-code-setup-for-beginners-using-c-and-cmake-e92ab4f1fba1)后, 我大致了解了CMakeLists.txt是什么东西。

首先VSCode对txt文档文件是没有字符识别算法支持的, 即没给txt文件里的字符添加Scope值, 主题插件也就无法对txt文档文件里的字符着色。
![image](https://user-images.githubusercontent.com/17448419/70512901-841a7b00-1b6b-11ea-94bc-b288be91f345.png)

但如果将txt文件命名为CMakeLists.txt, 它在VSCode里的"文件类型"(引号是因为后缀没变)居然就变了(感叹下txt文件的神奇), 并且有了一定字符识别算法支持。
![image](https://user-images.githubusercontent.com/17448419/70513391-7addde00-1b6c-11ea-886a-cd982abac87a.png)

遗憾的是支持程度还很粗浅, 如图, 符号括号字符连成一串, 无法细分。
![image](https://user-images.githubusercontent.com/17448419/70513721-1e2ef300-1b6d-11ea-99ad-202440ca9186.png)

另外CMakeLists.txt这个命名也很严苛, 无视大小写, 其它任何字符差别都会被别VSCode识别成txt文件, 失去字符识别算法支持。
![image](https://user-images.githubusercontent.com/17448419/70514480-b1b4f380-1b6e-11ea-9282-c183ad8ee973.png)

综上这个问题的回答是, 已添加CMakeLists.txt文件着色, 受限于算法支持, 还很简陋。

3,已着色, 不是有意为之, 遗漏。

---

这次调试C++文件, 发现一个特别尴尬的情况, 微软官方推荐的C/C++插件会导致部分字符颜色渲染错误。
![image](https://user-images.githubusercontent.com/17448419/70519299-ac5ba700-1b76-11ea-8ca3-50812219a20e.png)
这种渲染错误不是仅与Eva Theme冲突, 是会影响到所有主题插件。我已经向其提交了一个[issue](https://github.com/microsoft/vscode-cpptools/issues/4723), 不知道何时能得到解决(这个插件下的Open issues 1019个...)。您自行斟酌是否使用它, 如果能找到替代插件最好。

**Comment by fisheva** [comment]
cpptools团队回复很快, 有解决办法了, 关闭cpptools对部分字符渲染影响的方式是在setting里搜索colorization, 选择Disabled这个选项。
![image](https://user-images.githubusercontent.com/17448419/70694098-c5409580-1cf9-11ea-9c11-56ab942b4035.png)

**Comment by roy-tian** [comment]
作者很用心，很是让人感动！如果我是个土豪，肯定会给你donate 8000块。
不过 cpp 插件还是不要关闭增强着色选项，他那个我感觉不算着色错误，留着的话会根据语义提供更丰富的着色。（不过貌似官方这个选项有bug，会偶尔失灵，重新打开vscode又可能会好，不知道这里有什么我不知道的魔法）
总之作者这么用心肯定会成为享誉国内外的 带 工 程 师。请务必 加 带 力 度。
