### ISSUE TITLE
特别棒！！！可以支持Android Studio吗！！！

### ISSUE THREAD

**Issue by skooal** [fisheva/Eva-Theme#31]
up up up up up # # #30

**Comment by fisheva** [comment]
谢谢夸奖! 前端内部流行编辑器除了VSCode, 还有WebStorm家族, Sublime, 这些都尚未支持.....实在没有精力去开辟新的"领地",<del>最大原因是我这个菜鸡还只会一点前端, Android Studio都没用过。</del>
