### ISSUE TITLE
终端下文件夹底色掩盖文字，导致无法看清文件夹名称的问题

### ISSUE THREAD

**Issue by lijian12345** [fisheva/Eva-Theme#33]
![image](https://user-images.githubusercontent.com/26590220/79798068-fc4f4380-838a-11ea-93ee-27565596a0aa.png)

类似上图，文件夹的底色太绿了，实在看不清里面的字是啥。。。

**Comment by fisheva** [comment]
很抱歉处理晚了, 由于我并没有多少Terminal使用经验, 微软官网的API说明也讲得很模糊, 所以一直不知道那些API和Terminal里的文字颜色对应关系。经过issue#35里的网友提示, 我有了个大概猜测, 刚更新了Eva Theme, 问题貌似解决了。如果您还在使用Eva Theme, 请更新到最新版本。

**Comment by lijian12345** [comment]
大佬666~

**Comment by fisheva** [comment]
有没有最新效果截图给我看下啊-_-||

**Comment by lijian12345** [comment]
![Code_HsghRvgveG](https://user-images.githubusercontent.com/26590220/92083174-311edd00-edf8-11ea-9a1e-04c30c7cc2df.jpg)
效果图如上233

**Comment by fisheva** [comment]
我感觉不好看...看来必须得我自己有Terminal使用经验才能调好

**Comment by lijian12345** [comment]
是最新版的233，系统是WSL2，shell是fish，好像是默认主题吧。。。可能跟这个fish的默认主题也有一定关系

**Comment by fisheva** [comment]
您好! 因为[issue 58](https://github.com/fisheva/Eva-Theme/issues/58)，我在1.6.4版本对Terminal的API颜色做了些改动。如果您发现，改动之后，Terminal下的某些文字看不清或背景色不合理，请告知我，并提供截图，我再修改。谢谢！

**Comment by lijian12345** [comment]
> 您好! 因为[issue 58](https://github.com/fisheva/Eva-Theme/issues/58)，我在1.6.4版本对Terminal的API颜色做了些改动。如果您发现，改动之后，Terminal下的某些文字看不清或背景色不合理，请告知我，并提供截图，我再修改。谢谢！

好的大佬哈哈，不过我现在用的zsh+powerlevel10k好像没有底色了囧。。。
