### ISSUE TITLE
Such a great theme but the shortcuts are not showing up

### ISSUE THREAD

**Issue by max-programming** [fisheva/Eva-Theme#34]
![theme](https://user-images.githubusercontent.com/51731966/80933256-9332eb80-8de0-11ea-97da-6b66c816c7ea.png)

I have shown a comparison of the theme to the default theme. And it is not showing up the shortcuts. Also shown this in one of my videos: https://youtu.be/mrM-fQSEb84?t=352

One more thing. Pls if you can add a different color for React components and different for React tags. And also if you can add some kind of borders as in the default theme. Because everything looks mixed up. 😊

**Comment by fisheva** [comment]
Sorry to reply you late. 

The startup interface text bug has been fixed. Please update Eva Theme to the latest version if you still use it.

The color of React tags must be consistent with the color of tags in HTML, so it cannot be changed.

The logical sequence of Component color origin is:

First set pink for the Class, then the scope values of Component and Class are exactly the same , so the color of Component can't be changed. And Class can extend from Component, they are very similar in form and definition, so their color should be consistent too.

Finally, your programming instructional video on YouTube is very well done!
