### ISSUE TITLE
终端的 npm 和 yarn 的颜色过亮导致看不清楚

### ISSUE THREAD

**Issue by CTY9364945** [fisheva/Eva-Theme#36]
如题目，npm和yarn为亮黄色，太刺眼了

**Comment by fisheva** [comment]
可否先提供一下截图。

然后查看下您的Eva Theme版本是不是升到了0.8.0, 如果没有, 升到该版本, 再查看下。几天前更新的 0.8.0版刚对Terminal里的颜色调整了一波, 但我不知道调整的对不对, 因为我没什么Terminal使用经验_(:з」∠)_

如果升到0.8.0 问题还在, 请再提供下截图

**Comment by CTY9364945** [comment]
已升级至0.8.0





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fisheva/Eva-Theme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上9:43
收件人:&nbsp;"fisheva/Eva-Theme"<Eva-Theme@noreply.github.com&gt;;
抄送:&nbsp;"Angeladaddy007"<947903772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fisheva/Eva-Theme] 终端的 npm 和 yarn 的颜色过亮导致看不清楚 (#36)





 
可否先提供一下截图。
 
然后查看下您的Eva Theme版本是不是升到了0.8.0, 如果没有, 升到该版本, 再查看下。几天前更新的 0.8.0版刚对Terminal里的颜色调整了一波, 但我不知道调整的对不对, 因为我没什么Terminal使用经验_(:з」∠)_
 
如果升到0.8.0 问题还在, 请再提供下截图

**Comment by fisheva** [comment]
截图呢?

**Comment by CTY9364945** [comment]
没有吗？我发过去了呀，我再附件发一次，刚才是选择的图片




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fisheva/Eva-Theme"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月1日(星期二) 晚上9:51
收件人:&nbsp;"fisheva/Eva-Theme"<Eva-Theme@noreply.github.com&gt;;
抄送:&nbsp;"Angeladaddy007"<947903772@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fisheva/Eva-Theme] 终端的 npm 和 yarn 的颜色过亮导致看不清楚 (#36)





 
截图呢?

**Comment by fisheva** [comment]
还是没有, 难得碰到次和提issue的同时在线, 您加下我QQ 277042602? 交流方便点

**Comment by fisheva** [comment]
您好! 因为[issue 58](https://github.com/fisheva/Eva-Theme/issues/58)，我在1.6.4版本对Terminal的API颜色做了些改动。如果您发现，改动之后，Terminal下的某些文字看不清或背景色不合理，请告知我，并提供截图，我再修改。谢谢！
