### ISSUE TITLE
这个颜色会不会过于丑了一点

### ISSUE THREAD

**Issue by Arichy** [fisheva/Eva-Theme#37]
### Screenshot

![image](https://user-images.githubusercontent.com/29599723/93343185-c7281e00-f862-11ea-83c9-3ca24784208d.png)

终端是zsh+item2+agnoster
要被丑哭+亮瞎了😭能不能换回去啊
### Code Snippet

```

```

**Comment by fisheva** [comment]
哈哈, 来个更全面的截图吧, terminal的颜色因为不知道对应关系, 所以我全部给了个不同颜色, 有反馈我也好调整, 没反馈说明还行, 我terminal用场景太少了

**Comment by fisheva** [comment]
来个全面截图, 同时切换到 默认主题, 再截个图我看看, 谢谢

**Comment by Arichy** [comment]
> 来个全面截图, 同时切换到 默认主题, 再截个图我看看, 谢谢
这是全面截图，随便找了个仓库模拟我工作时的场景
![image](https://user-images.githubusercontent.com/29599723/93344776-a82a8b80-f864-11ea-80ad-2a2c4c6cd7ba.png)

这是默认主题
![image](https://user-images.githubusercontent.com/29599723/93344877-c4c6c380-f864-11ea-9ccc-e6716446c39b.png)

**Comment by fisheva** [comment]
OK 我马上调整。

**Comment by fisheva** [comment]
<img width="620" alt="WX20200916-214812@2x" src="https://user-images.githubusercontent.com/17448419/93346295-67337680-f866-11ea-9328-27383693d5bf.png">
能不能弄个相同操作, 让我看看这块Eva Theme下是什么样的

**Comment by Arichy** [comment]
> <img alt="WX20200916-214812@2x" width="620" src="https://user-images.githubusercontent.com/17448419/93346295-67337680-f866-11ea-9328-27383693d5bf.png">
> 
> 能不能弄个相同操作, 让我看看这块Eva Theme下是什么样的, 还是截全屏

![image](https://user-images.githubusercontent.com/29599723/93348206-7fa49080-f868-11ea-905d-a4c115046086.png)

**Comment by fisheva** [comment]
刚发布了0.9.5版本, 可能要过几分钟用户端才能收到, 您看到后更新下。最后还希望您更新后能再提供下这张图的Eva Dark和Eva Light下的截图, 非常感谢!
![image](https://user-images.githubusercontent.com/17448419/93350502-4f122600-f86b-11ea-8a3d-d56d3caec0b9.png)

**Comment by Arichy** [comment]
> 刚发布了0.9.5版本, 可能要过几分钟用户端才能收到, 您看到后更新下。最后还希望您更新后能再提供下这张图的Eva Dark和Eva Light下的截图, 非常感谢!
> ![image](https://user-images.githubusercontent.com/17448419/93350502-4f122600-f86b-11ea-8a3d-d56d3caec0b9.png)

我这里看到最新版本是0.9.4
![image](https://user-images.githubusercontent.com/29599723/93354401-884c9500-f86f-11ea-9dd1-c195ba4d8462.png)
不过颜色修改已经生效了
![image](https://user-images.githubusercontent.com/29599723/93354494-a3b7a000-f86f-11ea-9deb-56518453358f.png)

**Comment by fisheva** [comment]
嗯 0.9.5只改了npm那几个字, 可否给我看下Light下是什么样子, 毕竟我只是按对应关系改的Light, 不知道那边怎么样

**Comment by Arichy** [comment]
> 嗯 0.9.5只改了npm那几个字, 红字貌似还可以该深点。可否给我看下Light下是什么样子, 毕竟我只是按对应关系改的Light, 不知道那边怎么样。

![image](https://user-images.githubusercontent.com/29599723/93355430-a49d0180-f870-11ea-816c-b129c4490ad4.png)

**Comment by Arichy** [comment]
不过我想请问一下改这里颜色的目的是什么呢，之前的版本颜色都还挺不错的🤔

**Comment by fisheva** [comment]
有好几个issue都提说Terminal里的颜色有问题, 然后我又一直不知道对应关系, 想到干脆全部先给不同颜色, 这样用户反馈时, 我就知道怎么改了。

**Comment by fisheva** [comment]
谢谢! 您的反馈非常有帮助!
顺便给你看下目前还不知道的Terminal API应用位置, 红框里的就是, 如果发现有颜色不恰当的地方, 欢迎再提issue~
![image](https://user-images.githubusercontent.com/17448419/93356539-e0849680-f871-11ea-9323-35dfaa5506ea.png)

**Comment by Arichy** [comment]
> 谢谢! 您的反馈非常有帮助!
> 
> 顺便给你看下目前还不知道的Terminal API应用位置, 红框里的就是, 如果发现有颜色不恰当的地方, 欢迎再提issue~
> 
> ![image](https://user-images.githubusercontent.com/17448419/93356539-e0849680-f871-11ea-9323-35dfaa5506ea.png)
> 
> 

好的，感谢拯救我的眼睛🤓

**Comment by fisheva** [comment]
昨晚又做了点调整, 如果可以, 有劳您更新到0.9.7后再提供下这张图的Eva Dark和Eva Light 2个版本的截图, 带有npm err!字的。不好意思, 反复让您提供截图, 关于这张图, 应该是最后一次了_(:з」∠)_
![image](https://user-images.githubusercontent.com/17448419/93406311-eace8100-f8c1-11ea-8a32-7377db98258e.png)

**Comment by Arichy** [comment]
> 昨晚又做了点调整, 如果可以, 有劳您更新到0.9.7后再提供下这张图的Eva Dark和Eva Light 2个版本的截图, 带有npm ERR!字的。不好意思, 反复让您提供截图, 关于这张图, 应该是最后一次了_(:з」∠)_
> ![image](https://user-images.githubusercontent.com/17448419/93406311-eace8100-f8c1-11ea-8a32-7377db98258e.png)

![image](https://user-images.githubusercontent.com/29599723/93415489-3428cb80-f8d6-11ea-9c8d-282bb0cbfaf8.png)

![image](https://user-images.githubusercontent.com/29599723/93415538-50c50380-f8d6-11ea-9f8f-b357630d43f8.png)

**Comment by fisheva** [comment]
纳尼(ÒωÓױ)? 黄色和绿色位置怎么换了

**Comment by Arichy** [comment]
> 纳尼(ÒωÓױ)? 黄色和绿色位置怎么换了

没有换，我刚刚操作反了。。git clean的时候是绿色，不clean的时候是黄色
![image](https://user-images.githubusercontent.com/29599723/93415897-23c52080-f8d7-11ea-9345-b6442ff4c034.png)

**Comment by fisheva** [comment]
今天在操作Terminal时, 发现一处 Warning! 字符, 切到默认主题发现是金黄色的
<img width="778" alt="WX20200920-224532" src="https://user-images.githubusercontent.com/17448419/93714953-a7f9fb00-fb98-11ea-8579-374aad45d00d.png">


请问在这张图中, 金黄色也是代表一种警告吗? 
![#37-2](https://user-images.githubusercontent.com/17448419/93714979-dd9ee400-fb98-11ea-84d7-500ca685109a.png)


如果是的话, 后续版本应该会把Eva Theme里的上面的金黄色改成下面这种固有的Warning色
<img width="525" alt="WX20200920-231329@2x" src="https://user-images.githubusercontent.com/17448419/93714727-38374080-fb97-11ea-9c87-fa8cbf7e4130.png">

倒不是金黄色不好看, 而是这种颜色在Light下作为文字色会使文字完全看不清, 想要看清, 在Light下就得狂降亮度, 那样就失去统一性。所以我选了#F5625C这种橘红色作为警戒色, 无论是在Dark或Light下作为文字色或文字底色都很清晰。虽然作为底色它没有金黄色好看, 但我感觉表达方式的统一性>好看。

**Comment by Arichy** [comment]
> 今天在操作Terminal时, 发现一处 Warning 字符, 切到默认主题发现是金黄色的
> 
> <img width="778" alt="WX20200920-224532" src="https://user-images.githubusercontent.com/17448419/93714953-a7f9fb00-fb98-11ea-8579-374aad45d00d.png">
> 
> 
> 
> 
> 
> 请问在这张图中, 金黄色也是代表一种警告吗? 
> 
> ![#37-2](https://user-images.githubusercontent.com/17448419/93714979-dd9ee400-fb98-11ea-84d7-500ca685109a.png)
> 
> 
> 
> 
> 
> 如果是的话, 后续版本应该会把Eva Theme里的上面的金黄色改成下面这种固有的Warning色
> 
> <img width="525" alt="WX20200920-231329@2x" src="https://user-images.githubusercontent.com/17448419/93714727-38374080-fb97-11ea-9c87-fa8cbf7e4130.png">
> 
> 
> 
> 倒不是金黄色不好看, 而是这种颜色在Light下作为文字色会使文字完全看不清, 想要看清, 在Light下就得狂降亮度, 那样就失去统一性。所以我选了#F5625C这种橘红色作为警戒色, 无论是在Dark或Light下作为文字色或文字底色都很清晰。虽然作为底色它没有金黄色好看, 但我感觉表达方式的统一性>好看。

不是，这里的黄色是git不clean的标志，绿色是 clean的标志

**Comment by fisheva** [comment]
听起来有一点儿警示的意思, 不强烈。那先不改, 哪天发现Eva Theme里明显的Warning字符显示为金黄色, 再改。

**Comment by fisheva** [comment]
您好！因为[issue#58](https://github.com/fisheva/Eva-Theme/issues/58)，我在1.6.4版本对Terminal的API颜色做了些改动。如果您发现，改动之后，Terminal下的某些文字看不清或背景色不合理，请告知我，并提供截图，我再修改。谢谢！
