### ISSUE TITLE
If Variable Name is same to one of the Built-in Functions then Variable Color appears same as Calling a Function [Python]

### ISSUE THREAD

**Issue by REYNEP** [fisheva/Eva-Theme#39]
Eva 1.0.1

### Screenshot
![image](https://user-images.githubusercontent.com/35212190/99971644-ad0d3d80-2dc7-11eb-9e2e-18f67a98814b.png)

### Code Snippet
Python 3.7

```
input = input("Enter Something: ")
inputType = type(input)
x = self.draw_buttons(cur_context, UI_layout)
```

## Supplement
As of Eva 1.0.1 All **function-call** are Of Same colors, But I think in eva **_support.function.builtin.python_** are also same color as a **function-call.** Thus the variable gets the same color as a function-call, Wouldn't it be better if variables like 'input' were the same color as regular Variable

![image](https://user-images.githubusercontent.com/35212190/99971675-b8606900-2dc7-11eb-964a-b8750a1b183b.png)
![image](https://user-images.githubusercontent.com/35212190/99971700-beeee080-2dc7-11eb-8d5b-ea2ee5d5ab4c.png)
![image](https://user-images.githubusercontent.com/35212190/99971726-cb733900-2dc7-11eb-8275-c83b609a47ef.png)

**Comment by fisheva** [comment]
Thank you! This's a point I didn't notice. Is this the effect you wanted?
<img width="420" alt="QQ20201124-003646@2x" src="https://user-images.githubusercontent.com/17448419/99989753-f5d7ed00-2ded-11eb-8adc-4f4e81c40b6f.png">

**Comment by REYNEP** [comment]
Thanks For the fix, Got it in 1.0.2

**Comment by fisheva** [comment]
@REYNEP Sorry, it took so late to update with another fix. As you can see, I left a message for you on 2020-10-24, and I have been waiting for your reply.

**Comment by REYNEP** [comment]
@fisheva, Sorry for not replying, DEC 1 was deadline for a Short Film, That me and a friend was Working on for over a couple of months, WE were in Rush.... had to use some code for changing filenames, noticed that bug, So i thought I would just open a new issue here and assumed that you will fix it anyway....
