### ISSUE TITLE
Shouldn't the #define and #undef be of same color?

### ISSUE THREAD

**Issue by REYNEP** [fisheva/Eva-Theme#40]
As **#undef** is the reverse of **#define,** shouldn't they be of same color? The color of **#define** is fine.... so I think **#undef** should be of that color too...

currently, **#define 's** Scope **_keyword.control.directive.define_** is set to **_"foreground": "#A78CFA"_**
but **#undef** currently gets its color from **_keyword.control.directive_**
**#undef** has it's very own scope, which is **_keyword.control.directive.undef_**

 ![IMG1](https://user-images.githubusercontent.com/35212190/103676591-753f0b80-4fab-11eb-98e0-e547f880d0a5.png)

**Comment by fisheva** [comment]
Thanks for pointing out this detail! Please update Eva Theme to the latest version(1.0.2).

**Comment by REYNEP** [comment]
Thanks For the Quick Fix, @fisheva
