### ISSUE TITLE
Shouldn't a C++ Class constructor be of same color as destructor?

### ISSUE THREAD

**Issue by REYNEP** [fisheva/Eva-Theme#41]
Detructor is the opposite of Class Constructor.... Shouldn't they be of same color then? (+Italic)

The class constructor **_GHOST_SystemWin32_** 's color comes from the scope:- **_entity.name.function.definition.special.constructor.cpp_** which is set to **_"foreground": "#CF68E1"_** _(and also this is italic)_
But the class destructor **_~GHOST_SystemWin32_** gets it's color from **_entity.name.function_**

Class Destructors have a separate scope available:- **_entity.name.function.definition.special.member.destructor.cpp_**
These constructor and destructor ends with **_.cpp_** in their scope, As C doesn't support creating Classes, 

![image](https://user-images.githubusercontent.com/35212190/104514638-c7230980-561b-11eb-9225-a55db091f160.png)

**Comment by fisheva** [comment]
Fixed in 1.0.3 version.

"entity.name.function.definition.special.constructor.cpp", when I added this scope, I should have met a certain code like the "public" character in the picture is not displayed correctly. Then it also affected the class constructor. Now I delete this scope first, and when I met that kind of code again, I will add a more detailed scope.

**Comment by REYNEP** [comment]
@fisheva, Wait, so You are you talking about when you added the constructor's scope to the rule, and why you did that was because of some kind of mismatch of scope with "public", right?

> Sorry about writing the title in reverse way.... 😅 I really liked the Purple Color and the italic style, the constructor had before 😃. But It's Okay if making it blue makes more sense in terms of syntax....

(Sorry, for replying this late Me and My Friend Updated GPU, had to install windows, His all SATA Ports (Except 1) got covered by GPU, so had to exchange Stuffs with other people, did some benchmarks and tasted some games that I couldn't afford before)

**Comment by fisheva** [comment]
Yes, it is. 

(Last time, I didn't know the effect you wanted to modify, so I have been waiting for your reply. As long as you clearly describe the problem and the desired effect when you raise an issue, it doesn’t matter how late you reply.)
