### ISSUE TITLE
C++ function calls look different than C function calls

### ISSUE THREAD

**Issue by REYNEP** [fisheva/Eva-Theme#43]
**[_NOTE: I DON'T HAVE MS-C/C++ INSTALLED_]**

**_C++ functions Calls:-_** 
![image](https://user-images.githubusercontent.com/35212190/107937685-756cf680-6fae-11eb-9b3f-8cf02779ca3d.png)

**_Renamed the File to C:-_**
![image](https://user-images.githubusercontent.com/35212190/107937806-a64d2b80-6fae-11eb-8ab0-2de0154ecf15.png)

In C, **_meta.function-call.c_** and **_entity.name.function.c_** is set to `{ "foreground": "#56B7C3", "fontStyle": "italic" }`
![image](https://user-images.githubusercontent.com/35212190/107938111-1065d080-6faf-11eb-970d-029cc665b368.png)

In C++, **_entity.name.function_** is set to `{ "foreground": "#6494ED", "fontStyle": "" }`
![image](https://user-images.githubusercontent.com/35212190/107938188-2b384500-6faf-11eb-88db-96a2c4a66221.png)

> I Guess Eva-Theme Does use `{"foreground": "#56B7C3"}` for Function Calls, I checked python.... 

Then I checked Languages like lua, ruby, js, java, Function Calls (Their colors are not like Python's and C's Color)
JS and JAVA function calls get it's color from **_entity.name.function_** even though in both languages functions calls have **_meta.function-call_** which is the scope that python function call gets color from

 in lua, vscode textmate scope only adds **_support.function.any-method.lua_** and both lua and ruby function calls gets their color from **_support.function_**

**Comment by REYNEP** [comment]
**_[NOTE: I DON'T HAVE MS-C/C++ INSTALLED, HATE THAT ADDON]_**

**Comment by fisheva** [comment]
@REYNEP I apologize for this late reply. 

In C, the scope rule "meta.function-call.c entity.name.function.c" was originally added to distinguish between user-defined functions and language built-in functions(like "printf()"), but it seems that it can't be done at present. I have removed it. Please update Eva Theme to 1.0.4 .

**Comment by REYNEP** [comment]
It's Been so Long, and I hadn't replied.... My apology.... It seems like it looks same on C & C++ now.... Thank you


But in **_Python_** and some other language **_meta.function-call_** is still in play:
![image](https://user-images.githubusercontent.com/35212190/113509295-9d241800-9576-11eb-92cc-c5f57552c258.png)
![image](https://user-images.githubusercontent.com/35212190/113509325-c2b12180-9576-11eb-9a50-465f6be1c44b.png)

**Comment by fisheva** [comment]
It doesn't matter, just keep the font style consistent in the same language.

C and c++ have similar syntax and often call each other, which can be regarded as the same language in the theme configuration.

**Comment by REYNEP** [comment]
Yeah.... It's Kinda also Like I kind of Like both of the colors.... I personally was also thinking that Python should stay how it is.... 😄
