### ISSUE TITLE
Warnings and Errors

### ISSUE THREAD

**Issue by awgn** [fisheva/Eva-Theme#44]
Hello,

I really appreciate this theme. 

However, the color for warnings (orange) is sometimes misleading as it is too similar to the red one of errors (especially when errors are not present). 

Would it be possible to change it, for instance, to a lighter colour?

Thanks,
N.

**Comment by fisheva** [comment]
Hello, after receiving your issue, I tried to change all warning colors in Eva Theme to bright yellow #F8F900, or to Apple system yellow #FDBC40 (the minimize button color). While I feel that neither of them is suitable. Although they can attract my attention, they didn't make me feel a little warning effect.

My personal feeling is that the closer the color is to blood red, the stronger the sense of warning. So bright red means error, orange means warning.

So I will not modify the warning color of Eva Theme now. But I have selected all the warning-related options for you. You can copy the following options into your VSCode Setting.json, and modify the warning color as you like. Just replace all #F5625C in the following options. Some options are #F5625C59, 59 is the transparency setting, please keep it.

```json
"workbench.colorCustomizations": {
    "debugConsole.warningForeground": "#F5625C",
    "editorMarkerNavigationWarning.background": "#F5625C",
    "editorOverviewRuler.warningForeground": "#F5625C",
    "editorWarning.foreground": "#F5625C",
    "inputValidation.warningBackground": "#F5625C59",
    "inputValidation.warningBorder": "#F5625C",
    "list.warningForeground": "#F5625C",
    "minimap.warningHighlight": "#F5625C59",
    "terminal.ansiBrightYellow": "#F5625C", 
    "tokenColors":[{
        "scope":"token.warn-token",
        "settings":{
            "fontStyle":"",
            "foreground":"#F5625C"
        }
    }]
}
```

**Comment by cyh0** [comment]
It bothers me too.  
It's hard for me to distinguish between the two colors.

**Comment by fisheva** [comment]
Please update Eva Theme to 1.2.4. Although it is a little bit out of my personal color intuition, I have changed the warning color from orange to yellow.
