### ISSUE TITLE
将warnning颜色换成黄色

### ISSUE THREAD

**Issue by elve960520** [fisheva/Eva-Theme#47]
warning！！！为什么要用红色！！！
warning使用黄色就很舒服，红色有强迫症！！！
导致我以为满篇的error！！！

**Comment by fisheva** [comment]
确切的说Eva Theme的warning用的是橘黄色，这是我个人比较习惯的警示色。而error的颜色用的是更鲜艳的血红色，我认为区别还是挺大的。可能刚从别的主题过来会不习惯。
您这么多感叹号，让我怀疑是不是有的地方设置错了，改是橘黄色的位置设置成了血红色？请提供下代码，让我在本地测试下谢谢。
如果确实是warning颜色困扰到了您，请先在个人设置里调成您习惯的颜色,下面是与warning有关的API :

  "workbench.colorCustomizations": {
      "debugConsole.warningForeground": "#F5625C",
      "editorMarkerNavigationWarning.background": "#F5625C",
      "editorOverviewRuler.warningForeground": "#F5625C",
      "editorWarning.foreground": "#F5625C",
      "inputValidation.warningBackground": "#F5625C59",
      "inputValidation.warningBorder": "#F5625C",
      "list.warningForeground": "#F5625C",
      "minimap.warningHighlight": "#F5625C59",
      "terminal.ansiBrightYellow": "#F5625C", 
      "tokenColors":[{
          "scope":"token.warn-token",
          "settings":{
              "fontStyle":"",
              "foreground":"#F5625C"
          }
      }]
  }

**Comment by elve960520** [comment]
哈哈哈，感叹号没有恶意，但是我确实在我的机器上，试用eva dark这个主题的时候，vscode编辑go程序，由于涉密，无法将代码文件发出来，但是确实可能因为橘黄色的原因（因为没有修改的地方，直接加载的插件），在暗黑主题下显得很亮
并且在经过测试后，确实是橘黄色，存在以下对于我个人体验不好的地方：
1.橘黄色在暗黑主题下与血红色对比不明显，会误认为是error
2.在文件有error的时候，warning就不显示了，当然这个我想有您的设计在里面
另:这个主题确实很好看，期待作者做的更加完美

**Comment by fisheva** [comment]
请将Eva主题更新为1.2.4，warning颜色已从橙色改为黄色。

**Comment by fisheva** [comment]
虚线是的 unused symbol的提示，我觉得变暗效果不好，影响观看。

**Comment by heroboy** [comment]
`xxx: number`虚线就划了一半，感觉很不好。
对于字符数比较少的虚线也不美观。

**Comment by fisheva** [comment]
划一半是VSCode本身的问题，主题决定不了。
这点不美观，相比变暗的效果，两权其害取其轻吧_(:з」∠)_
