### ISSUE TITLE
侧边栏选中指示缺失

### ISSUE THREAD

**Issue by dulltackle** [fisheva/Eva-Theme#48]
开发者你好, 我遇到的问题如下:

### 问题描述

* 其它主题

    [![gm3nVU.gif](https://z3.ax1x.com/2021/05/03/gm3nVU.gif)](https://imgtu.com/i/gm3nVU)

    [![gn0Ew9.png](https://z3.ax1x.com/2021/05/04/gn0Ew9.png)](https://imgtu.com/i/gn0Ew9)

    如上图所示, 在通过选中侧边文件栏中的小控件来创建文件的过程中, 会给出灰色小框提示已经选中创建按钮

* Eva Light

    [![gm3NVO.gif](https://z3.ax1x.com/2021/05/03/gm3NVO.gif)](https://imgtu.com/i/gm3NVO)

    [![gn00Og.png](https://z3.ax1x.com/2021/05/04/gn00Og.png)](https://imgtu.com/i/gn00Og)

    而在 Eva Light 中并没有这样的提示

### 版本信息

* Eva-Theme 版本: 1.1.8
* VSCode 版本: 1.55.2
* 操作系统: Windows 10

**Comment by fisheva** [comment]
![image](https://user-images.githubusercontent.com/17448419/116963500-93a7e000-acdb-11eb-9d81-5056571312ab.png)
您好！
新建文件，文件即被选中，这个被选中的背景色其实是有颜色的，只是和旁边的标题栏区分度不大。我把它标红，您可以看到二处颜色是相同的。
![image](https://user-images.githubusercontent.com/17448419/116963509-9c001b00-acdb-11eb-9917-55a9f5fb221f.png)
我曾考虑过把这二处颜色设为鼠标滑动在文件标题上的浅蓝色，但最终否决了。因为我觉得看一个文件是否被选中，主视觉注意力在横向的标题栏。
![WX20210504-131600@2x](https://user-images.githubusercontent.com/17448419/116963552-bafead00-acdb-11eb-8df1-68d660fcd51e.png)
而竖向文件的被选中背景色，是种次要的视觉辅助。如果设置过于鲜明的颜色，我觉得是种视觉干扰，注意力浪费。
所以这种和标题栏不大的颜色区分度，是我特意为之的，这是我的观点/设计理念吧。

**Comment by dulltackle** [comment]
你好, 开发者, 感谢你的回复

很抱歉, 我似乎没有表达清楚我遇到的问题, 我进一步详细了上文中的问题描述

希望这一次我的表达足够清晰 :)

**Comment by fisheva** [comment]
额，我想我没理解错，我录2个给你看颜色是怎么转变的，就是这么设计的_(:з」∠)_
![屏幕录制1](https://user-images.githubusercontent.com/17448419/116977649-45073f80-acf5-11eb-8030-541ccf066dbc.gif)
![屏幕录制2](https://user-images.githubusercontent.com/17448419/116977670-4afd2080-acf5-11eb-81fc-0acb5eab3ac9.gif)

**Comment by fisheva** [comment]
如果您觉得这个颜色和您的期望不符，可以在设置文件setting.json里添加下面选项，更改里面的颜色，调成您自己喜欢的颜色。PS:下面是现用的白色，Eva Light用的hover效果浅蓝色是 #0065FF19。
"workbench.colorCustomizations": {
      "list.inactiveSelectionBackground": "#EDF0F7",  
}

**Comment by dulltackle** [comment]
[![gnxFPJ.gif](https://z3.ax1x.com/2021/05/04/gnxFPJ.gif)](https://imgtu.com/i/gnxFPJ)

唔, 我个人认为, 如果存在像上图中的橘色指示边框, 可以直观地在侧边栏各个部件间切换

[![gnxrzn.gif](https://z3.ax1x.com/2021/05/04/gnxrzn.gif)](https://imgtu.com/i/gnxrzn)

在 Eva Light 中就只能凭感觉了...

当然, 我尊重并欣赏开发者你的美学思考, 你对浅色的理解真的非常独到 :)

**Comment by fisheva** [comment]
原来您指的图标上的框，真的是我理解错了，抱歉！哈哈哈哈！请告诉我下您做示例的黄色背景主题叫什么？我还不知道这个API是哪个。Eva Theme实现这个提示效果不会是加边框，而是改变背景色。

**Comment by dulltackle** [comment]
演示的主题是 VSCode 内置的浅色主题 Solarized Ligtht,
Bluloco Light Theme 的侧边栏相关设计我个人觉得也值得参考 :)

**Comment by fisheva** [comment]
我在您说的这2个主题上都没看到按钮上的边框...
这个主题是什么？
![123](https://user-images.githubusercontent.com/17448419/117095855-1becba80-ad9a-11eb-837f-5b449f85b4a6.gif)

**Comment by dulltackle** [comment]
不好意思, 我好像忽略了一个关键点: 出现这样的边框是因为用快捷键移动了焦点...

[![gK6Rcn.gif](https://z3.ax1x.com/2021/05/05/gK6Rcn.gif)](https://imgtu.com/i/gK6Rcn)

我把使用到的快捷键添加到了图片里, 这样应该可以复现效果了 :)

上图中的主题是 Bluloco Light Theme

**Comment by fisheva** [comment]
OK, 已解决，请更新Eva Theme至1.1.9
顺便问下您这个添加快捷键的gif制作工具叫什么？看着挺好用。

**Comment by dulltackle** [comment]
辛苦了, 开发者 :)

PS: 添加按键是 ScreenToGif 里自带的功能, 非常好用!
