### ISSUE TITLE
Markdown 行内代码块着色

### ISSUE THREAD

**Issue by dulltackle** [fisheva/Eva-Theme#51]
开发者你好, 我希望 Markdown 中的行内代码可以有明显独立的着色

* Eva Theme

    [![gaO3nK.png](https://z3.ax1x.com/2021/05/11/gaO3nK.png)](https://imgtu.com/i/gaO3nK)

    从上图中可以看到用 \`\` 包裹的代码和普通文字没有明显区别

* Dark

    [![gaOttH.png](https://z3.ax1x.com/2021/05/11/gaOttH.png)](https://imgtu.com/i/gaOttH)

    希望可以实现和上图类似的效果 :)

---

* Eva Theme 版本: 1.2.0
* VSCode 版本: 1.56.0
* 操作系统: Windows 10

**Comment by dulltackle** [comment]
我使用的主题是 VSCode 内置的 Dark(Visual Studio)

但是我这里查看的 scope 值好像是不一样的

[![gdFFje.png](https://z3.ax1x.com/2021/05/11/gdFFje.png)](https://imgtu.com/i/gdFFje)

[![gdFEBd.png](https://z3.ax1x.com/2021/05/11/gdFEBd.png)](https://imgtu.com/i/gdFEBd)

**Comment by fisheva** [comment]
找出是哪个插件了吗？

**Comment by dulltackle** [comment]
唔, 情况似乎变得稍微有点复杂了, 我尝试关闭了所有的插件, 但 scope 值依然是不同的

[![g0mjfJ.png](https://z3.ax1x.com/2021/05/12/g0mjfJ.png)](https://imgtu.com/i/g0mjfJ)

因为我的 VSCode 进行了很多配置, 不太好控制变量, 所以我现在正在下载 Windows 镜像, 打算也用虚拟机测试一下

等我的好消息 :sunglasses:

**Comment by dulltackle** [comment]
呃, 似乎情况不太妙

[![g0QkDI.png](https://z3.ax1x.com/2021/05/12/g0QkDI.png)](https://imgtu.com/i/g0QkDI)

- 虚拟化引擎: hyper-v
- 虚拟机中系统: Windows 10 家庭版
- 虚拟机中 VSCode 版本: 1.56
- 虚拟机中 VSCode 主题: Dark+(default dark)

可以看到上图中行内代码的 scope 是独立的

要不我再看看别的 Windows 主机, MAC 的话我这边就没有了

**Comment by fisheva** [comment]
我今天在一台win10台式机上试过，和我Mac和Win10虚拟机里Scope值是一样的, 只是我没截图....

**Comment by fisheva** [comment]
你把你打的这句示例粘贴到这里下

**Comment by dulltackle** [comment]
`printf("hello, world");` 是非常著名的一段代码

**Comment by dulltackle** [comment]
我知道了!!! 行内代码的标记不是单引号 \', 而是 \`

**Comment by fisheva** [comment]
啊 这...最多也只能实现前面句color成字符串颜色，待后续版本一起加上吧。

<img width="626" alt="WX20210512-231952@2x" src="https://user-images.githubusercontent.com/17448419/118000652-98723100-b378-11eb-888b-3637b630e003.png">
回到这个issue最初的问题，经过这一通操作，你能看到制作主题也有限制，能否实现Markdown行内代码块着色，要看VSCode是否提供了足够细致的Scope支持。

**Comment by dulltackle** [comment]
OKOK, 辛苦了开发者 :)
