### ISSUE TITLE
光标颜色和参考线颜色相同，导致光标看不到了

### ISSUE THREAD

**Issue by thiswind** [fisheva/Eva-Theme#53]
我非常喜欢这个配色，尤其是Light配色。但是有一个小问题希望能解决一下。就是Python的缩进参考线的颜色、宽度与光标一模一样，光标很容易被遮挡导致找不到。

### Screenshot
![image](https://user-images.githubusercontent.com/23764/118597955-00dd6a00-b7e0-11eb-861a-22b12e1e0305.png)

https://github.com/fisheva/Eva-Theme/blob/167b1b36ef24557c6fa637c5bdc3794b0d2a2568/themes/Eva-Light.json#L63
就这里，光标和另外6个东西的颜色是相同的。UP主的审美这么优秀，请UP主换一个光标的颜色吧，然后UP主重新发布一下，我们在vscode里update一下，就解决了

这样直接要求很不礼貌，可是最近暂时没有时间来阅读源码写PR，只好求UP主帮忙改改，谢谢😊🌹

**Comment by thiswind** [comment]
最近暂时没有时间来阅读源码写PR，只好求UP主帮忙改改，谢谢😊🌹

**Comment by fisheva** [comment]
尝试了下，发现如果光标的样式是细线的话，确实会有这个问题。
<img width="491" alt="WX20210519-080604@2x" src="https://user-images.githubusercontent.com/17448419/118738324-5a45a780-b879-11eb-9536-b8367bc61310.png">
<img width="560" alt="WX20210519-080521@2x" src="https://user-images.githubusercontent.com/17448419/118738325-5a45a780-b879-11eb-89f5-d6c15eef05a5.png">

我平常用的是粗线，即使和对齐线重合，还是能看出差别。
<img width="502" alt="WX20210519-230814@2x" src="https://user-images.githubusercontent.com/17448419/118837291-3f197d00-b8f7-11eb-8c3d-6cdfa960781a.png">
<img width="563" alt="WX20210519-230804@2x" src="https://user-images.githubusercontent.com/17448419/118837326-4476c780-b8f7-11eb-916b-5c8e3a091610.png">

最初光标我设置的是类似函数的蓝色，直到了解一点Vim编辑器后，在VSCode里安装Vim插件
<img width="690" alt="WX20210519-231153@2x" src="https://user-images.githubusercontent.com/17448419/118837705-ac2d1280-b8f7-11eb-84df-7d898c2b2273.png">
才发现Vim模式光标始终是块状
<img width="499" alt="WX20210519-231352@2x" src="https://user-images.githubusercontent.com/17448419/118838040-ee565400-b8f7-11eb-8146-90ce4b391a69.png">
<img width="441" alt="WX20210519-231509@2x" src="https://user-images.githubusercontent.com/17448419/118838217-15ad2100-b8f8-11eb-9881-c57cbbb2d041.png">

这种模式下如果光标还是蓝色，就和对括号的透明橘黄色很不协调，而VSCode目前还未给不同光标样式做API区分。

line模式下，橘黄色略差于蓝色; block模式下，橘黄色远胜于蓝色。综合考虑，就将光标颜色定为了橘黄色。

不过您可以在VSCode的设置setting.json文件里添加：

```json
"workbench.colorCustomizations": {
        "editorCursor.foreground": "#6495EE",
    },
```
就可以自行设置光标颜色了。

**Comment by thiswind** [comment]
非常感谢 UP 主提供的颜色，
<img width="814" alt="WX20210523-202550@2x" src="https://user-images.githubusercontent.com/23764/119260375-1a7a1980-bc05-11eb-8998-70aba0ca26bb.png">
