### ISSUE TITLE
Support full semantic highlighting

### ISSUE THREAD

**Issue by madrussa** [fisheva/Eva-Theme#54]
First thing, your theme is lovely.

It would be really good if Eva theme could enable semantic highlighting properly. I find it extremely useful to be able to identify variables that are actually parameters. This means I can avoid overwriting them or quickly seeing where they're used

On line 16 we can see `assetId` is yellow, but on lines 17 and 18 the `assetId` param is white.
![image](https://user-images.githubusercontent.com/1470257/120787788-a0f8fa00-c527-11eb-8399-156cbf1a41bd.png)

If we toggle the semanticHightlighting setting to true (overriding the theme)

Now on lines 17 and 18 the `assetId` param usage is coloured the same (yellow).
![image](https://user-images.githubusercontent.com/1470257/120788052-ee756700-c527-11eb-93ee-e830054d3513.png)

This does however mean that a lot of the colours in the file have changed. On line 21 `asset` is now orange because it reflects the const usage on line 17. I guess there'll be a lot of these little nuances to get right and would likely require a separate "Eva Dark Semantic" theme. 

Keep up the great work!

**Comment by fisheva** [comment]
Could you please copy the code here? Thank you.

**Comment by madrussa** [comment]
Sure, here is a much simpler example.

Typescript:
```typescript
import React, { HTMLProps } from "react";
import cx from "classnames";
import styles from "../my-styles.module.scss";

type TProps = {
	children: React.ReactNode;
	className?: string;
};

type TComponentProps = HTMLProps<HTMLDivElement> & TProps;

const Container: React.FunctionComponent<TComponentProps> = ({ children, className, ...htmlProps }) => {
	return (
		<div {...htmlProps} className={cx(styles.container, className)}>
			{children}
		</div>
	);
};

export default React.memo(Container);
```

Semantic Hightlighting: **Off**
![image](https://user-images.githubusercontent.com/1470257/120801964-c7279580-c539-11eb-803f-8dc28eea59ce.png)

Semantic Hightlighting: **On**
![image](https://user-images.githubusercontent.com/1470257/120802002-d3135780-c539-11eb-98e5-efb0bad45ed9.png)

---

Also when paramters are pushed onto multiple lines they are no longer yellow:

Semantic Hightlighting: **Off**
![image](https://user-images.githubusercontent.com/1470257/120802184-0bb33100-c53a-11eb-9dcf-e9bd8d36b186.png)

Semantic Hightlighting: **On**
![image](https://user-images.githubusercontent.com/1470257/120802855-d1965f00-c53a-11eb-835d-e9ed38e34037.png)

---

Hopefollow the following article will be of some use:
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by fisheva** [comment]
First, thank you for taking me to discover this feature of VSCode, I haven't opened it before. The link you provided is also very helpful, thank you so much!

I am going to learn how the code is colored when this feature is turned on. Then deal with the problem you mentioned and reply to you tomorrow.

**Comment by EikelFlo** [comment]
I completely agree, your theme is really nice and thank you for taking the time and effort to implement that feature as I too think it would be very useful

**Comment by fisheva** [comment]
Sorry for being late.

After reading the Semantic Highlight Guide, and using it in Eva Theme on my personal computer, I find it solves some problems, but brings some new problems.

I have always wanted to mark parameters in functions, the Syntax Highlight couldn't do it, the Semantic Highlight makes it.
<img width="1680" alt="123" src="https://user-images.githubusercontent.com/17448419/120932305-d5d39f80-c727-11eb-885f-b03dbe0f2a76.png">
 
But Semantic Highlight has a rule that I feel not good. As long as it is turned on, some predefined rules will be enforced. Can't add exact rules from zero like Syntax Highlight.
<img width="747" alt="WX20210606-235904@2x" src="https://user-images.githubusercontent.com/17448419/120932452-61e5c700-c728-11eb-82cc-ae9062a7a3a7.png">

The Semantic Highlight rule is overlaid on the Syntax Highlight rule. Moreover, the granularity of Semantic Highlight is not as exact as Syntax Highlight. One Semantic Highlight rule can often cover multiple Syntax Highlight rules.

I tried to write a Semantic Highlight rule, without color, hoping to disable it, but failed.
<img width="585" alt="WX20210607-005735@2x" src="https://user-images.githubusercontent.com/17448419/120933493-01a55400-c72d-11eb-9804-bd7459687f47.png">

And Semantic Highlight rules do not support transparent colors.
<img width="505" alt="WX20210607-011211@2x" src="https://user-images.githubusercontent.com/17448419/120933600-68c30880-c72d-11eb-89e8-0aa3e06e6e1b.png">

Regardless of whether the semantic analysis of Semantic Highlight is correct, this excessively intrusive change to the existing color system makes me cautiously turn it on.

So I won't open Semantic Highlight in Eva Theme for the time being unless I can find a way to disable the predefined Semantic Highlight rules and then add exact new rules one by one.

You can still force it on through the Semantic Highlight setting : ON.

**Comment by madrussa** [comment]
Thanks for looking into this, I appreciate that this behaviour can be tricky. I look forward to more updates from you!

**Comment by cns1rius** [comment]
## Partial Highlighting Missing in Some Languages

I've been using it for a long time and feel that it's the most comfortable theme I've ever used, but there are a lot of parts that are close to white. Today, I remembered to look for the open-source code, and found that it's still being maintained:)

It's mainly the variable parts of most languages why?:(, but some special types are not configured (see the bold part below)

### textmate scopes

- **storage.type.byte.go**
- **storage.type.annotation.java; meta.declaration.annotation.java; meta.class.body.java; meta.class.java; source.java**(这些是同一个字符的textmate scopes，下同)
- **meta.method.body.java; meta.method.java; meta.class.body.java; meta.class.java; source.java**
- **support.variable.magic.python**
- **meta.function-call.arguments.python; meta.function-call.python; meta.member.access.python; source.python**
- variable.other.assignment.*
- variable.other.*
- variable.other.readwrite.alias.js; meta.block.js; meta.import.js; source.js; source.vue

### Test Codes

[test.zip](https://github.com/user-attachments/files/21071762/test.zip)

Your theme is really nice and thank you for taking the time and effort to implement features

**Comment by fisheva** [comment]
@cns1rius Hi, sorry for late reply. I just updated Eva Theme, and the following image is a character color supplement for the scope you mentioned. For the remaining scopes that have not been added, I think it's better to keep them as they are.

<img width="2459" height="382" alt="Image" src="https://github.com/user-attachments/assets/b98dc671-a287-47c5-87a6-daf8f6c02198" />

**Comment by cns1rius** [comment]
> [@cns1rius](https://github.com/cns1rius) Hi, sorry for late reply. I just updated Eva Theme, and the following image is a character color supplement for the scope you mentioned. For the remaining scopes that have not been added, I think it's better to keep them as they are.
> 
> <img alt="Image" width="2000" height="382" src="https://private-user-images.githubusercontent.com/17448419/467407908-b98dc671-a287-47c5-87a6-daf8f6c02198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI3NDAwNjksIm5iZiI6MTc1MjczOTc2OSwicGF0aCI6Ii8xNzQ0ODQxOS80Njc0MDc5MDgtYjk4ZGM2NzEtYTI4Ny00N2M1LTg3YTYtZGFmOGY2YzAyMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE3VDA4MDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZTNkZDAwMzdkMTE5MTE1ODAwNzMwZGQ5ZmE1MWE5NTAxMmZiOTA4YTY0NGI0YmQxYWI1OGMxYzZhN2Q1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CfZ9zybu4SvsuOFBlQTrs2IoJBQQB22CTAg2TFpxCCE">

Thank you for the quick fix! Really appreciate your work on eva theme and the effort you put into maintaining it.
