### ISSUE TITLE
求问下大佬使用的字体是什么？

### ISSUE THREAD

**Issue by ryzejiang** [fisheva/Eva-Theme#59]
很喜欢这个主题，求问下大佬，readme中介绍用的例图中使用的字体是什么？

**Comment by fisheva** [comment]
字体是 [CamingoCode](https://www.fontsquirrel.com/fonts/camingocode).

**Comment by ryzejiang** [comment]
> 字体是 [CamingoCode](https://www.fontsquirrel.com/fonts/camingocode).

感谢~
