### ISSUE TITLE
请问有webstorm版吗

### ISSUE THREAD

**Issue by 12548** [fisheva/Eva-Theme#6]
rt

**Comment by fisheva** [comment]
确实我刚开始用的是Webstorm, 这套主题最初雏形也是在Webstorm设置的, 不过在遇到VSCode后就再也不想用Webstorm了.....然后就把这套主题搬到了VSCode上(0.0.1版本), 目前这套主题版本是0.2.6, 迭代很多了, 但中间很多是关于VSCode的界面UI更新, 编程语言着色的更新倒是较少, 主要在0.0.1版本就完成了80%以上的语言着色(Webstorm的界面UI也不能自定义)。Webstorm的那个主题, 我没做成Webstorm插件, 只是本地设置, 文件还保留着在(但抱歉, 我不会去更新了, Webstorm都删了), 你如果要, 留个邮箱。遇到和现有VSCode上显示不一样的地方, 可以在VSCode里用ctrl+shift+P 输入Scope, 回车, 调用查看Scope工具, 查看字符颜色, 然后在Webstorm里设置下就可以了。

**Comment by 12548** [comment]
谢谢！

**Comment by orochi14** [comment]
链接失效了，哎

**Comment by orochi14** [comment]
> 谢谢！



> 谢谢！

能发一份给我吗？119859336@qq.com，谢谢

**Comment by fisheva** [comment]
抱歉,很多天没上线...让你久等了。WebStorm版是这款主题的第一版,后来转VSCode后,就没更新了,大概有当前版本的70%的内容, 不过确实没精力去更新WebStorm版了。我下面放个链接, 同时邮箱也给您发一份。
链接: https://pan.baidu.com/s/1dL_eHo8pRJvIQo0mM6r8DA 提取码: 52fp
