### ISSUE TITLE
Modify the matching bracket pair color

### ISSUE THREAD

**Issue by ghost** [fisheva/Eva-Theme#60]
At the moment, matching brackets are colored with a light shade of the cursor color, which makes it hard to figure out where the cursor is, especially of the brackets are nearby and the cursor is a block.

![image](https://user-images.githubusercontent.com/58289453/128836590-cbaf073e-90a1-458f-a840-46ace3d6c0df.png)
![image](https://user-images.githubusercontent.com/58289453/128836702-02db6438-11fe-4cb7-8015-a268ea9c2ec2.png)

### Code Snippet

```python
D[1,2]
```

**Comment by fisheva** [comment]
There are only two APIs that can be set for the match bracket. 

```
"editorBracketMatch.background": "#FF90707F",
"editorBracketMatch.border": "#FF907000",
```

No matter which way I mark match bracket, it will affect the display of the cursor.

You can customize the brackets color in VSCode setting.json.

```
"workbench.colorCustomizations": {
"editorBracketMatch.background": "#FF90707F",
"editorBracketMatch.border": "#FF907000",
}
```

Or just turn off this feature through following setting.
![企业微信截图_20210818194343](https://user-images.githubusercontent.com/17448419/129909075-bb38b5f6-0acf-491f-8aa1-67c587c0f064.png)
