### ISSUE TITLE
注释斜体可否为可选项？

### ISSUE THREAD

**Issue by hjlong00** [fisheva/Eva-Theme#61]
你好，很喜欢这个主体，很好看。
但能否增加注释字体斜体的可选项？
或有可以更改的方法提供？

**Comment by fisheva** [comment]
<img width="622" alt="WX20210829-193108@2x" src="https://user-images.githubusercontent.com/17448419/131248934-775cc397-4fa6-4e1d-a3e7-5a664e4a14a4.png">
<img width="621" alt="WX20210829-193130@2x" src="https://user-images.githubusercontent.com/17448419/131248936-dc8bba24-d2a6-49aa-b14f-2df125b8b08d.png">

有斜体模式的

**Comment by hjlong00** [comment]
额。我意思是不要斜体， 使用 eva dark模式的时候， 注释都是斜体，我想要正的

**Comment by fisheva** [comment]
将下面这段复制进 VSCode的 setting.json里
```json
    "editor.tokenColorCustomizations": {
        //使所有主题注释都使用正体字
        "comments": {
            "fontStyle": "",
        },
        //也可单独设置某个主题下的注释改为正字
        "[Eva Dark]": {
            "comments": {
                "fontStyle": "",
            }
        },
        "[Eva Light]": {
            "comments": {
                "fontStyle": "",
            }
        },
    },
```
参考链接 https://geek-docs.com/vscode/vscode-tutorials/vscode-modify-editor-color-matching.html

**Comment by hjlong00** [comment]
可以了 太感谢了
