### ISSUE TITLE
请区分一下 return 对象中变量与方法的颜色

### ISSUE THREAD

**Issue by i0air** [fisheva/Eva-Theme#62]
例如

``` typescript
export function useFeature(){
  const foo = 'foo';
  const bar = () => {
    console.log('Hello world');
  }
  return { foo, bar } // These two should have different colors
}
```

**Comment by fisheva** [comment]
![企业微信截图_20210909153601](https://user-images.githubusercontent.com/17448419/132643158-7001a3fc-d26d-400f-bd7d-e2109a2c9bb5.png)
![企业微信截图_20210909153611](https://user-images.githubusercontent.com/17448419/132643168-73ed8e31-8530-4eb2-932a-ee9e5d01cee8.png)
区分不了，因为VSCode给它们的Scope值是完全相同的。

**Comment by i0air** [comment]
![image](https://user-images.githubusercontent.com/7053897/132782573-36889635-7153-490a-850b-7e9ef1541836.png)
有些主题是可以的，能参考它们的实现吗？

**Comment by fisheva** [comment]
![企业微信截图_20210910093740](https://user-images.githubusercontent.com/17448419/132784896-49dc5a7f-f067-4c97-b0aa-07645c9977ad.png)
![企业微信截图_20210910093753](https://user-images.githubusercontent.com/17448419/132784899-b5571159-4392-4f74-920d-8a9275465b66.png)
默认主题用的是semantic highlight功能实现的，为什么Eva Theme尚未使用semantic highlight，我在这个[issue#54](https://github.com/fisheva/Eva-Theme/issues/54)里有说明, 最后一段。

**Comment by i0air** [comment]
非常感谢你的回复，我将继续关注#54的进展。
