### ISSUE TITLE
Improve built-in TS/JS inlay hints readability for Eva light themes

### ISSUE THREAD

**Issue by gulshan** [fisheva/Eva-Theme#64]
The newly introduced TS/JS inlay hints in VSCode are not quite readable in my eyes-
![image](https://user-images.githubusercontent.com/751732/133929042-4cc36af8-119d-49b5-a8c2-3583277ca303.png)

The built-in lights themes in Code are showing these inlay hints text in black or dark grey. Can you please have a look?

Thanks for the nice themes!

**Comment by fisheva** [comment]
<img width="615" alt="WX20210919-223005@2x" src="https://user-images.githubusercontent.com/17448419/133931364-a6ab92f9-83f8-441b-ad31-506a3fae5ba5.png">
This is how this code looks on my computer, maybe you should check if it is caused by other extensions.
<img width="720" alt="WX20210919-223153@2x" src="https://user-images.githubusercontent.com/17448419/133931548-95b923c3-cb31-428d-bf44-c40941d724a5.png">

**Comment by gulshan** [comment]
These settings has to be enabled in vscode for inlay hints to show up-
```json
"javascript.inlayHints.variableTypes.enabled": true,
"javascript.inlayHints.functionLikeReturnTypes.enabled": true,
"typescript.inlayHints.variableTypes.enabled": true,
"typescript.inlayHints.functionLikeReturnTypes.enabled": true,
```

**Comment by fisheva** [comment]
I copied the settings into my VSCode setting.json. And restarted VSCode. But there is still nothing changed.
<img width="1679" alt="WX20210920-120619@2x" src="https://user-images.githubusercontent.com/17448419/133956683-25b15852-3933-46ca-b5c5-0ecb3f27d72a.png">

My email is fishyu_eva@qq.com. Would you mind sending this typescript file to me?

**Comment by gulshan** [comment]
Some information to reproduce minimally-
VSCode version: 1.60.1 (stable-user)

Add 1 line to settings:
```json
"typescript.inlayHints.variableTypes.enabled": true
```

Test typescript code:
```ts
let str = 'hi'
```

It should look like this with "Eva Light" theme-
![image](https://user-images.githubusercontent.com/751732/133959517-3431cb42-bc6f-4fa7-ac33-b91572ec517f.png)

**Comment by gulshan** [comment]
Also, adding this settings-
```json
 "workbench.colorCustomizations": {
    "editorInlayHint.foreground": "#654"
}
```
improves the readability:
![image](https://user-images.githubusercontent.com/751732/133960549-455ecd61-7e97-46e6-94f9-a680f4c90f23.png)

**Comment by fisheva** [comment]
That's really quite strange...
<img width="1618" alt="WX20210920-135523@2x" src="https://user-images.githubusercontent.com/17448419/133961694-e6111f69-5184-4309-9d7c-6434084dcf05.png">
<img width="420" alt="WX20210920-135536@2x" src="https://user-images.githubusercontent.com/17448419/133961698-8c1a1d3a-dff0-4596-a420-624ebe7d41cc.png">

These two APIs exist, indicating that there are indeed these settings. According to your screenshots, I will set them like this in the next version. These are CSS property-name colors.

```
"editorInlayHint.foreground": "#888888 "  //Eva Light
"editorInlayHint.foreground": "#8A97C3 "  //Eva Dark
```

**Comment by gulshan** [comment]
It looks good now-
![image](https://user-images.githubusercontent.com/751732/134638248-92b123be-ca77-4efa-9f0b-df86520afef6.png)

Closing the issue!
