### ISSUE TITLE
In dark mode, the title bar's color is still black

### ISSUE THREAD

**Issue by XDu2022** [fisheva/Eva-Theme#68]
### Screenshot

![image](https://user-images.githubusercontent.com/30729729/147378535-e63484c0-7375-4d5f-8ba9-78d74f691c73.png)

## Supplement

When the code window is displayed independently, the color of the title bar is difficult to read

**Comment by fisheva** [comment]
Thank you for pointing out this bug!

Eva Theme for VS is converted from Eva Theme for VSCode using theme-converter-for-vs. I tested and found that there is no VSCode UI API that can control the color of this font.

![企业微信截图_16406897527485](https://user-images.githubusercontent.com/17448419/147560360-e88536e3-a01d-4185-bcc7-16d731b41df3.png)
(Screenshot in test mode, the font were not setted to any other color)

 I will submit an iusse to the theme-converter-for-vs team and ask them how to solve it or to provide an API. Then I will fix this.

**Comment by XDu2022** [comment]
Thanks for your attention. I really like this color scheme, and I will use Eva Theme for a long time.

**Comment by fisheva** [comment]
Hi @XDu2022 , this bug has been fixed in 0.0.4 version.
