### ISSUE TITLE
Border shadow too strong.

### ISSUE THREAD

**Issue by Whitessx** [fisheva/Eva-Theme#70]
### Screenshot

![Untitled](https://user-images.githubusercontent.com/89744868/147857385-5e46cf77-f088-443b-99f7-144c4a1c3dc7.png)

### Code Snippet

```

```

## Supplement
  Hi. Considering most of the theme is flat, this shadow stands out very much. It might be a matter of taste, but in the store screenshots this doesn't appear to be the case.

**Comment by fisheva** [comment]
Do you mean this shadow? (I turn it red)
![1D17D884-089C-43A7-8129-104F6D1B2705](https://user-images.githubusercontent.com/17448419/147881956-71228a13-a7ed-46a4-8cab-50118f339f12.png)
This is a feature of VSCode, which is used to prompt the user that there is still content on above. When the page scrolls to the top,  it will disappear.

If you don't like it. Copy these code into your VSCode settings.json file. Then it will never show.

```json
"workbench.colorCustomizations": {
        "scrollbar.shadow": "#00000000",
}
```
