### ISSUE TITLE
 Problem with colors of  "const", "let" and "var"

### ISSUE THREAD

**Issue by heorhii-aksiuk** [fisheva/Eva-Theme#72]
Why I have problem with colors of  "const" and "var"? They are white, but must be purple. 
v1.7.7

### Screenshot
![image](https://user-images.githubusercontent.com/81520242/150433973-3061fbc2-b262-4065-85fd-b25733aae53c.png)

**Comment by fisheva** [comment]
Could you please copy your complete code here? For me to find out the reason. Thanks!

**Comment by heorhii-aksiuk** [comment]
The problem is there regardless of my code. I tried opening other files, projects, restarting the program and the computer, installing previous versions of the theme. Other themes continue to highlight these keywords without any problems.

**Comment by heorhii-aksiuk** [comment]
Can I fix this locally using settings?

**Comment by fisheva** [comment]
These words are not showing wrong everywhere, I need to restore your code, see what's wrong with their scope values. In your screenshot, I can't see the full code.

Of cause, you can fix that in local settings, but it is a little complicated. Please copy your code and let me see, if it is a common problem, let me fix it. Thanks!

**Comment by fisheva** [comment]
These words are not showing wrong everywhere, I need to restore your code, see what's wrong with their scope values. In your screenshot, I can't see the full code.

Of cause, you can fix that in local settings, but it is a little complicated. Please copy your code and let me see, if it is a common problem, let me fix it. Thanks!

**Comment by heorhii-aksiuk** [comment]
Okey, here is example of simple code

```
const a = 5;
let b = 10;

function example(a, b) {
  var c = 15;
  return a + b * c * d;
}

add(a, b);
```

Screen of Eva Dark theme(and all 6 Eva themes give same result)
![image](https://user-images.githubusercontent.com/81520242/150567273-597b3813-a1e9-4664-b817-c8d4ffca79e2.png)

Screen of One Dark Theme(and all of other themes work right)
![image](https://user-images.githubusercontent.com/81520242/150567755-e07700a8-3ec4-46f0-818e-c209c9fbcfb1.png)

I really love your theme, I spent about 10 hours and tried dozens of themes to find it, no other theme suits me, and I would really like to solve this problem. Hope for help

**Comment by heorhii-aksiuk** [comment]
And I don't know what that mean, but I have text "Preview" in extension title. All my other extensions don't have this text
![image](https://user-images.githubusercontent.com/81520242/150570283-996edcd3-1702-4ed2-8f41-6064f215498b.png)

**Comment by heorhii-aksiuk** [comment]
And it's work when I change .js to .ts !
![image](https://user-images.githubusercontent.com/81520242/150571735-4766823d-1e91-4567-9e37-500de42b9dac.png)

**Comment by heorhii-aksiuk** [comment]
Found the source of the problem. Extensions that change the default settings for a language.
![image](https://user-images.githubusercontent.com/81520242/150578781-5a04293f-f51b-42dd-869c-b31ede35e0aa.png)
![image](https://user-images.githubusercontent.com/81520242/150578799-d6e06fac-29c0-4c7f-92cf-f6ea3554189e.png)

**Comment by fisheva** [comment]
Yes, someone has raised an issue because of this plugin before.
