### ISSUE TITLE
React components color

### ISSUE THREAD

**Issue by loficolors** [fisheva/Eva-Theme#77]
Hi,
how can I change the color of react components? 
Now JSX elements and components are red, it's not very convenient

![image](https://user-images.githubusercontent.com/106006679/172029655-9a62d054-4571-4e74-8315-093f74da5f70.png)

**Comment by fisheva** [comment]
All theme plugins add color to characters based on their scope value. You can check the scope value of all characters by pressing Ctrl+Shift+P (Windows) or Cmd+Shift+P (Mac) and selecting Inspect TM Scopes. Then adjust their color in settings.
<img width="1447" alt="企业微信20220605-173401@2x" src="https://user-images.githubusercontent.com/17448419/172044652-201b00ba-cec4-477f-83ec-0f24a3f516a5.png">

```json
"editor.tokenColorCustomizations": {
        //control Eva Dark only
        "[Eva Dark]": {
            "textMateRules": [
                {
                    "scope": "support.class.component",
                    "settings": {
                        "foreground": "#ff0000",
                        "fontStyle": "bold"
                    },
                },
            ],
        },
        //control all Themes
        "textMateRules": [
            {
                "scope": "support.class.component",
                "settings": {
                    "foreground": "#00ff00",
                    "fontStyle": "bold"
                },
            },
        ],
    },
```

**Comment by loficolors** [comment]
Thanks!
