### ISSUE TITLE
标签选项卡

### ISSUE THREAD

**Issue by JosnTom** [fisheva/Eva-Theme#78]
能否在激活的标签上加入明显的提示或者下划线，现有激活方式在黑暗模式下看的不是很清楚，经常容易搞混。

**Comment by fisheva** [comment]
尝试了很多颜色都觉得加了边线后有点打破界面的连贯性，暂时不会添加。您可以在settings.json里添加下列文字，自行设置。

![企业微信截图_20220607100451](https://user-images.githubusercontent.com/17448419/172280111-a6940907-3973-40a7-9d60-20b042ce844d.png)

```json
"workbench.colorCustomizations": {
      "tab.activeBorder": "#ff0000",
      "tab.activeBorderTop": "#00ff00",
}
```
