### ISSUE TITLE
如何取消括号背景色（着色）？

### ISSUE THREAD

**Issue by wfnian** [fisheva/Eva-Theme#79]

**Comment by fisheva** [comment]
抱歉回复晚了，不知道为什么现在有新issue没有邮件提醒了_(:з」∠)_

将这个设置调成never就行了。
![129909075-bb38b5f6-0acf-491f-8aa1-67c587c0f064](https://user-images.githubusercontent.com/17448419/176837822-9dd20e77-41da-4c22-bb1f-04f50b124cee.png)
