### ISSUE TITLE
请问有意向适配 IDEA 吗

### ISSUE THREAD

**Issue by zhimarin** [fisheva/Eva-Theme#80]
非常好看的主题，感谢作者。
很想在 IDEA 中也应用该主题，但是在 IDEA 的插件商店搜索未果。
请问作者后续有意向适配 IDEA 吗？
谢谢！

**Comment by Jokin613** [comment]
同求

**Comment by zhimarin** [comment]
> 在不确定什么时候能做出来时，不敢随意给承诺...

期待！
