### ISSUE TITLE
在外接显示器上正红色似乎有点模糊。

### ISSUE THREAD

**Issue by jxxiao** [fisheva/Eva-Theme#81]
我的设备是m1 macbook pro，外接了飞利浦279c9的4k显示器，正红色比如示例图片中的git:(master)，master就是模糊的，我观察了一下，这个颜色的字体都是糊的。

**Comment by fisheva** [comment]
额.....没法因为这个原因修改其颜色。分支名，是一个十分重要，需要警示，但警示程度低于error的文字，所以设为了红色，但鲜艳程度略低于error。
我设置主题颜色的基准电脑也是一台macbook pro (2014)，是否模糊，我也只能以这上面为准。

**Comment by jxxiao** [comment]
我观察了一下，在macbook pro上显示是正常的，但是一到外接显示器就会糊。我看了一下其他项目中使用这个颜色，也是一样的情况，应该是一个普遍问题，像git(master)这种error设置成这样能理解。暗色版本的self也有同样的问题，示例图片中的this也是一样的。这个问题只会在外接的显示器上较为明显。

**Comment by fisheva** [comment]
主题的设置里，没办法区分使用环境...所以只能以MacBook pro上的显示为准了。
