### ISSUE TITLE
VS2022无法导入Fonts and Colors文件

### ISSUE THREAD

**Issue by Yan-S-R** [fisheva/Eva-Theme#83]
### Screenshot

![image](https://user-images.githubusercontent.com/98587018/196470384-3ef20e02-651d-4e0a-bd46-20850bb14e11.png)

**Comment by fisheva** [comment]
我从README里留的下载地址，下载下来后，在自己电脑上的测试了下，能导入。我猜测可能是VS版本不同，.vssettings的文件有些许差异。
![企业微信截图_20221019104132](https://user-images.githubusercontent.com/17448419/196584897-03a5efd2-0c38-4f03-85fd-2fa62110516a.png)
您先在您的VS上尝试导出一份设置，导出步骤：工具→导入和导出设置→导出选定的环境设置→导出的设置里，取消全选，只勾选 选项>环境>字体和颜色 选项。导出后，对比这个文件（后面用“A文件“指代）和Eva Dark.vssettings。文件里的标签，带有 Foreground=“颜色代码” 或 Background=“颜色代码”，是设置各种文字颜色的标签，这类标签不会影响兼容性。除开这些标签，其它标签就有可能影响兼容性，以A文件为标准，一点点修改Eva Dark.vssettings文件，然后在VS里尝试导入，应该改出一个可以导入的版本（没准修改第一行 ApplicationIdentity version="17.0" 就可以了）。
![企业微信截图_20221019110500](https://user-images.githubusercontent.com/17448419/196587761-354c514b-1bba-4a4e-95d8-67d6a31eded8.png)
过程有点复杂，但我只能想到这种调试方法。VS主题制作的官方支持相比VSCode落后很多，没有文档，UI靠VSCode主题转换而来，syntax也没有VSCode里这种方便查看代码Scope值的工具，只能用.vssettings文件做补充，设置 字体和颜色 时，选项没有代码示例，只能看选项名理解....您这个issue让我知道，这个补充，还有导入兼容性问题，太难了_(:з」∠)_
![企业微信截图_20221019110946](https://user-images.githubusercontent.com/17448419/196589557-1b49ba17-677b-4c39-aad8-a0ed87c1be42.png)

**Comment by Yan-S-R** [comment]
十分感谢您的解答，我把原先下载的Eva Dark.vssettings打开后，发现里面有乱码，可能是之前下载时出现了错误，重新下载文件后可以正常导入。很抱歉因为这种低级问题给您造成麻烦(Ｔ▽Ｔ)

**Comment by fisheva** [comment]
哈哈哈，没事~ 是个好消息。导入后，您也会发现，有些语法和VSCode上表现不一样，原因就是
![企业微信截图_20221019133826](https://user-images.githubusercontent.com/17448419/196607040-0eed734a-e6f0-4169-9c5c-fad128d95052.png)
如果您发现这种差异，并且对某个语言比较熟悉，找到了具体设置选项，可以再提issue告诉我，帮我完善 .vssettings文件，感谢！~
![企业微信截图_20221019134940](https://user-images.githubusercontent.com/17448419/196607818-5fbe3a0a-ee9d-44c1-9adb-74065e889ab6.png)
