### ISSUE TITLE
can support jupyter notebook

### ISSUE THREAD

**Issue by Justin3go** [fisheva/Eva-Theme#85]
### Screenshot

![image](https://user-images.githubusercontent.com/63507251/202669694-ef56cae3-eaef-4223-81df-5d2e1c066e1b.png)

### Code Snippet

```

```

**Comment by Justin3go** [comment]
也许可以这样：
```json
    "workbench.colorCustomizations": {
		// "editor.selectionBackground": "#e41fda7e",   //选中高亮
		// "editor.background": "#C7EDCC",       	  //背景颜色
		// "editor.foreground": "#C7EDCC",       	  //背景颜色
		// "input.border":"#ff0000"
		"editorPane.background": "#EBEEF5" // jupyter
	}
```
![image](https://user-images.githubusercontent.com/63507251/202690796-b07032b8-1f6e-4d98-8d35-d7beb8814c4b.png)

**Comment by fisheva** [comment]
不会用jupyter notebook，但大致看懂了你的issue: 文字编辑区域和代码块背景色相同了。

感谢直接指出了API！已更新在1.9.0版本。
