### ISSUE TITLE
Keyword colorization in java  is the same as class

### ISSUE THREAD

**Issue by UPIMMUNITY** [fisheva/Eva-Theme#86]
### Screenshot

Java Case

![Snipaste_2022-11-22_20-35-28](https://user-images.githubusercontent.com/77432836/203316903-6b3125fe-40dc-44ef-9185-412f4389c71b.png)

C# Case which is looking great

![Snipaste_2022-11-22_20-37-22](https://user-images.githubusercontent.com/77432836/203317689-68aaa81d-f6c9-41a2-a856-60c5f9276d99.png)

### Code Snippet

```Java
public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Hello World!");
    }
}
```
```C#
internal class Program
{
    public static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
    }
}
```

**Comment by rababR1** [comment]
Same with the `self` parameter in Python:
![image](https://user-images.githubusercontent.com/65360255/203426137-dde86880-fac0-48a0-81ee-32ac1c6e8dfe.png)

Compare that with `this` in JS:
![image](https://user-images.githubusercontent.com/65360255/203426265-c9752d94-d51a-4162-a291-cb258c0551fd.png)
Isn't `self` and `this` _are special key words?_ I have C_pp: Enhanced Colorization enabled.

**Comment by fisheva** [comment]
@UPIMMUNITY Thanks for providing bug sample! Fixed in 1.8.9 version.

@rababR1 It looks normal on my computer.
![企业微信截图_20221123152212](https://user-images.githubusercontent.com/17448419/203705916-cb6d0441-a8da-48cf-ad95-ddb958776db6.png)
When I turn on semantic Highlighting, it looks like yours. 
![企业微信截图_20221124140225](https://user-images.githubusercontent.com/17448419/203706464-f204977d-eacb-45f6-b59c-561afae2eb61.png)
Eva Theme doesn't support this feature yet, you can see why in [issue 54](https://github.com/fisheva/Eva-Theme/issues/54).

**Comment by UPIMMUNITY** [comment]
@fisheva 
Please add colorization for class access modifier `file` in CSharp.
A new access modifier `file` has been added in CSharp 11.

![Snipaste_2022-12-01_16-11-13](https://user-images.githubusercontent.com/77432836/205002090-3ca8e97a-5fe9-4c0a-9430-dec659d00072.png)

**Comment by fisheva** [comment]
`file` can't be set other color. Since its' scope value is a variable.
![企业微信截图_20221201183420](https://user-images.githubusercontent.com/17448419/205032021-7de4e583-d4b8-4c76-b490-f369a42ea606.png)
![企业微信截图_20221201183506](https://user-images.githubusercontent.com/17448419/205032041-4ed011d6-5db4-4a83-bb53-eb34fd760432.png)

All characters's scope value is given by VSCode. You can check them by pressing Ctrl+Shift+P (Windows) or Cmd+Shift+P (Mac) and selecting Inspect Editor Tokens and Scopes.
![企业微信截图_20221201184025](https://user-images.githubusercontent.com/17448419/205032086-34cb498b-a14c-49d9-ad62-59cddc1cc3d5.png)

**Comment by fisheva** [comment]
Yes, the build-in themes opened Semantic Highlighting, while Eva Theme doesn't. You can see why in [issue 54]( https://github.com/fisheva/Eva-Theme/issues/54).

**Comment by UPIMMUNITY** [comment]
@fisheva 
I noticed that vscode build-in themes have colorization for this keyword. It seems its color can be override? When I switch to a build-in theme, color of `file` also quickly switches.

![image](https://user-images.githubusercontent.com/77432836/205051870-4ee594d1-8e78-4d4e-a020-4de329ae152b.png)

As the gif shows, its color quickly changes from color for variable to color for keyword.
This happens for all build-in themes.

![bandicam 2022-12-01 20-19-55-327 00_00_00-00_00_30](https://user-images.githubusercontent.com/77432836/205053233-77f661ad-acc6-4530-ba89-563a388eef5f.gif)

**Comment by fisheva** [comment]
You can force open this featrue by setting this option `true`.
![企业微信截图_20221201204204](https://user-images.githubusercontent.com/17448419/205056084-e27d8b9c-f525-4d01-93ed-087fe51246c9.png)

**Comment by UPIMMUNITY** [comment]
> You can force open this featrue by setting this option `true`. ![企业微信截图_20221201204204](https://user-images.githubusercontent.com/17448419/205056084-e27d8b9c-f525-4d01-93ed-087fe51246c9.png)

I misquoted your first reply and I deleted it because it's too long. And accidently deleted my reply again. This is awkward...
Anyway, I have enable this setting however it's not working for this keyword.
It works fine for parameters.
![image](https://user-images.githubusercontent.com/77432836/205057657-160d08f7-384a-43ca-8934-22f796d5fd3f.png)

**Comment by fisheva** [comment]
![企业微信截图_20221201210659](https://user-images.githubusercontent.com/17448419/205061868-ce0c54f7-4811-455c-ba09-7f7ce9188c9e.png)
Semantic Highlighting doesn't work for `file` on my computer in either build-in themes nor Eva Theme. I guess there is another plug-in affected it in your computer. Please try enable/disable C_pp: Enhanced Colorization, then see it.
![企业微信截图_20221201211547](https://user-images.githubusercontent.com/17448419/205063712-f541fd00-128a-4dca-b6dc-1bdd8c7f8f48.png)

**Comment by UPIMMUNITY** [comment]
Semantic highlighting does work for `file` in my computer.
`"C_Cpp.enhancedColorization"` it has no effect on this issue.
And I have tried other themes that are not built-in. They all colorize `file` when semantic highlighting is enabled.

built-in Dark+
semantic highlighting on
![Snipaste_2022-12-02_00-11-21](https://user-images.githubusercontent.com/77432836/205202452-8e1132c6-61b4-424e-ac53-fd6a811e2fff.png)
semantic highlighting off
![Snipaste_2022-12-02_00-13-14](https://user-images.githubusercontent.com/77432836/205202457-38aa02f4-41cb-42d0-9f7f-6417ddff0d7b.png)

One dark pro
![Snipaste_2022-12-02_10-37-57](https://user-images.githubusercontent.com/77432836/205202643-7325d128-a635-452e-bf2d-3fe4b816d883.png)

JetBrains Darcula(by Anan)
![Snipaste_2022-12-02_00-09-47](https://user-images.githubusercontent.com/77432836/205203173-f19cf56c-c287-44d4-83b7-7d2be6feadfb.png)

JetBrains Rider Dark Theme(by Edwin Sulaiman)
![Snipaste_2022-12-02_10-31-18](https://user-images.githubusercontent.com/77432836/205203188-4e1a09da-1fe0-4658-8441-c7097a4528da.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
Semantic highlighting should work for `file` in Eva Theme in your computer too. I guess there is another plug-in added semantic scopes value for `file` in your computer.

**Comment by UPIMMUNITY** [comment]
@fisheva 
I've tested it in a virtual machine, a totally clean vscode with eva theme and C# extension installed only.
Semantic highlighting still not working for `file`.
![image](https://user-images.githubusercontent.com/77432836/205238617-47b6beab-2bb6-4441-a0b9-6ffdbb57435b.png)

**Comment by fisheva** [comment]
Does semantic highlighting work for `file` in build-in themes in the virtual machine ?

**Comment by UPIMMUNITY** [comment]
@fisheva 
Yes it does work in virtual machine with built-in theme.
![image](https://user-images.githubusercontent.com/77432836/205264933-ce3ad0df-0e3c-4357-a799-600ff0a5b91d.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
Still in virtual machine VScode, switch to Eva Theme, then give me a screenshot of `file` scopes value. Thx

**Comment by UPIMMUNITY** [comment]
@fisheva 
![image](https://user-images.githubusercontent.com/77432836/205290875-3b69c553-8a4b-4c93-8f7b-99168e768e6e.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
This really confused me.  I enabled semantic highlighting, but there is no semantic token type in `file` scopes value, either in build-in themes nor in Eva Theme.
![企业微信截图_20221202204323](https://user-images.githubusercontent.com/17448419/205301409-3bf6547e-9446-4c04-93fc-25ab849bd998.png)
![企业微信截图_20221202204200](https://user-images.githubusercontent.com/17448419/205301421-3e00bac1-dbb1-43b8-aa4c-8f2ab87fc390.png)

Please try the following steps:
1) Turn current theme to Eva Dark.
2) Find the folder where VSCode stores plug-ins. Find Eva Theme folder.
![企业微信截图_20221202211834](https://user-images.githubusercontent.com/17448419/205301636-46444b15-ddf9-4cd0-9a9a-229c38048612.png)
3) Open it, open thems folder, open Eva-Dark.json.
4) Add `, keyword.cs` at the end of the scope property value in line 722.
5) Restart VSCode, check the scopes value of `file`.

**Comment by fisheva** [comment]
If the above steps still do not work, then only try the ultimate debugging way. Here is my debugging way when I encounter such a situation with unknown reasons and no clue.
1) Turn current theme to Eva Dark.
2) Find the folder where VSCode stores plug-ins. Find Eva Theme folder.
4) Open it, open thems folder, open Eva-Dark.json.
5) Comment some codes, restart VSCode, and see if the display is restored to the initial value. In your case, you need to check whether the scope value of the file is the same as that in the build-in themes after each VSCode restart. 
![企业微信截图_20221202213149](https://user-images.githubusercontent.com/17448419/205308800-dc4e017c-ab0e-4692-b90f-9d5075aa54ef.png)
6) Comment half of the code every time. Repeat this process to find out which part of the code affects it.

**Comment by UPIMMUNITY** [comment]
Now it works
![image](https://user-images.githubusercontent.com/77432836/205312663-25804196-0849-4d56-991d-5e9e68a037ee.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
Finally! A hard won result. Thanks! The process of debugging with you has given me a new understanding of the principle of semantic highlighting.
The `file` scopes value has been updated in 1.9.2 version.

**Comment by UPIMMUNITY** [comment]
@fisheva 
Well done! My pleasure.

**Comment by UPIMMUNITY** [comment]
@fisheva 
Another issue in latest version.
Colorization for keywords of primitive type and `void` in csharp is the same as access modifier.
Obviously it was caused by adding `, keywords` in the scope property.

Before update(it is pink)
![image](https://user-images.githubusercontent.com/77432836/205429177-8362b320-3491-48ff-978c-6ad7823f288c.png)

After update(it is purple)
![Snipaste_2022-12-03_14-45-19](https://user-images.githubusercontent.com/77432836/205429208-80dd5fd7-b97f-4bde-b370-7dca3ef2fecf.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
Sorry for reply late. 

This is why Eva Theme doesn't support Semanti Highlighting yet, which I mentioned in [issue 54](https://github.com/fisheva/Eva-Theme/issues/54).

The Semantic Highlighting rule is overlaid on the Syntax Highlighting rule. While, the granularity of Semantic Highlighting is not as exact as Syntax Highlighting. One Semantic Highlighting rule can often cover multiple Syntax Highlighting rules.

By the way, why are the scope values in my computer so different from yours, which makes it difficult for me to debug. Here is my VSCode version.
![企业微信截图_20221207110437](https://user-images.githubusercontent.com/17448419/206081205-9c6118a6-85fb-4225-96d5-28cc285f82e7.png)

**Comment by fisheva** [comment]
@UPIMMUNITY 
I'm confused... I uninstall 1.70.0 VSCode. Installed 1.73.1 VSCode, then only installed Microsoft C# and Eva Theme, enabled Semantic Highlighting, there is still no semantic token type in `void` and `string` scopes value.
![企业微信截图_20221207154512](https://user-images.githubusercontent.com/17448419/206119501-6a9e0eae-c67e-4a3a-a8d5-6651d6525aa4.png)
![企业微信截图_20221207154409](https://user-images.githubusercontent.com/17448419/206119520-b95fb1cb-9b99-4aa4-abda-701e0a9a6377.png)

At present, you'd better disable Semantic Highlighting to get the best Eva Theme experience, while the `file` keyword will not show purple.
