### ISSUE TITLE
Add activityBar margin highlight as many themes have

### ISSUE THREAD

**Issue by UPIMMUNITY** [fisheva/Eva-Theme#87]
![Snipaste_2022-11-22_21-26-04](https://user-images.githubusercontent.com/77432836/203330412-2b1af5f1-e149-4b2f-be64-f58a237ce879.png)
Just like this icon, a little light in the margin of where activityBar is docked.
In both eva light and eva dark, it's a little hard to tell which activity page is currently displayed without margin hightlight. And I didn't find corresponding property in settings.json to override this feature. If there is one, please let me know!

**Comment by fisheva** [comment]
Personally, I don't like to set the active button too bright. I think if the brightness is too high, it will attract too much attention. You can custom it's color in settings.json:

```json
"workbench.colorCustomizations": {
        "activityBar.foreground": "#96A4CD",
}
```

**Comment by UPIMMUNITY** [comment]
> Personally, I don't like to set the active button too bright. I think if the brightness is too high, it will attract too much attention. You can custom it's color in settings.json:
> 
> ```json
> "workbench.colorCustomizations": {
>         "activityBar.foreground": "#96A4CD",
> }
> ```

I misexpressed myself. What I actually want to customize is `"activityBar.activeBorder"`. Anyway I've found the right property to modify. Thank you! And yes I appreciate and respect your design concept. `"activityBar.foreground"` is currently pretty and keeping it as it is is just great.
```json
  "workbench.colorCustomizations": {
        "activityBar.activeBorder": "#96A4CD"
    }
```
