### ISSUE TITLE
Please make the "tab.activeBorderTop" same as "tab.border" in vscode

### ISSUE THREAD

**Issue by gulshan** [fisheva/Eva-Theme#88]
I think making the `"tab.activeBorderTop"` same as `"tab.border"` (color of the sides of the tab border) in vscode will make the active tab easier to notice.

**Comment by fisheva** [comment]
@gulshan 
I like current style. But you can custom it by put these into your settings.json.
```json
"workbench.colorCustomizations": {
    "[Eva Light]": {
        "tab.activeBorderTop":"#aaadb499", //custom color
    },
    "[Eva Dark]": {
        "tab.activeBorderTop":"#181a1f", //custom color
    },
},
```

**Comment by gulshan** [comment]
I have already done that. Thought it would be a good idea to be the default in the theme.

**Comment by fisheva** [comment]
Thanks for your proposal, I prefer the current style.
