### ISSUE TITLE
The api of canvas that moveTo() is not bold

### ISSUE THREAD

**Issue by shmilybaozi** [fisheva/Eva-Theme#9]
![_20180710231014](https://user-images.githubusercontent.com/36563636/42519419-9b4ffdbc-8496-11e8-8a42-033222db69cf.jpg)

**Comment by fisheva** [comment]
这个问题出在VSCode给 moveTo() 这个方法分配的Scope值与其他函数不同, 所以主题层面没法解决。算是VSCode代码字符识别的一个小BUG。
![2](https://user-images.githubusercontent.com/17448419/42638846-3c650b62-8621-11e8-80f4-f92402c4032f.png)
![1](https://user-images.githubusercontent.com/17448419/42638861-4314628c-8621-11e8-9daf-27848b3dbcfb.png)
