### ISSUE TITLE
.js文件与.vue文件，变量声明关键字未着色

### ISSUE THREAD

**Issue by MrFlyHouse** [fisheva/Eva-Theme#90]
### Screenshot

![bug1](https://user-images.githubusercontent.com/102533859/210174097-1d768ee4-181b-43f6-974a-b393592ca79b.png)
![bug2](https://user-images.githubusercontent.com/102533859/210174098-16ecce4e-1e5d-4f58-9dba-049223f956b1.png)
![设置](https://user-images.githubusercontent.com/102533859/210190817-866da318-8479-4daf-91ca-0b1878f5fafc.png)

### Code Snippet

`.js` file
```js
// foo.js
const pName = "llal";
const job = "coder";
let num = 1;
var boolVar = true;
```
`methods` part in `<script>`, `.vue` file
```vue
// role.vue
handleUpdate(row) {
      this.dialogFlag = "edit";
      this.reset();
      const roleId = row.roleId || this.ids
      const roleMenu = this.getRoleMenuTreeselect(roleId);
      // some other code
},
```

## Supplement

js文件和vue文件<script>部分中的变量声明关键字（`var`，`let`，`const`）没有出现高亮，
设置界面没有`enhancedColorization`这一条设置项，还有其他排查点么……
还请开发者确认情况，辛苦了

**Comment by fisheva** [comment]
@MrFlyHouse 
![企业微信截图_20230102093939](https://user-images.githubusercontent.com/17448419/210190071-e3f60ec8-f68c-4bb3-a320-5f51c0078131.png)
![企业微信截图_20230102094018](https://user-images.githubusercontent.com/17448419/210190074-efb6f007-20b6-4dc2-9736-26b539f498f2.png)
这是在我VSCode里的显示效果，你遇到的这种情况一般是有别的插件影响到了这些字符的scopes值，在README里有提到。
![企业微信截图_20230102094720](https://user-images.githubusercontent.com/17448419/210190204-2f44640b-f55f-474d-8a37-7c73e4bc72ca.png)
你试试在设置里搜索`enhancedColorization`, 设置这个选项为`disabled`
![企业微信截图_20230102094923](https://user-images.githubusercontent.com/17448419/210190233-b3fc5919-24af-4edd-a562-9ae6677ad195.png)

**Comment by MrFlyHouse** [comment]
> @MrFlyHouse ![企业微信截图_20230102093939](https://user-images.githubusercontent.com/17448419/210190071-e3f60ec8-f68c-4bb3-a320-5f51c0078131.png) ![企业微信截图_20230102094018](https://user-images.githubusercontent.com/17448419/210190074-efb6f007-20b6-4dc2-9736-26b539f498f2.png) 这是在我VSCode里的显示效果，你遇到的这种情况一般是有别的插件影响到了这些字符的scopes值，在README里有提到。 ![企业微信截图_20230102094720](https://user-images.githubusercontent.com/17448419/210190204-2f44640b-f55f-474d-8a37-7c73e4bc72ca.png) 你试试在设置里搜索`enhancedColorization`, 设置这个选项为`disabled` ![企业微信截图_20230102094923](https://user-images.githubusercontent.com/17448419/210190233-b3fc5919-24af-4edd-a562-9ae6677ad195.png)

您好，我想咨询一下，您是否了解Babel JavaScript的语义化着色功能该如何关闭呢？确实是这个扩展和您的主题之间出现了字符颜色冲突

**Comment by fisheva** [comment]
@MrFlyHouse 上面已经给出操作说明了额，在VSCode的settings.json里，搜索`enhancedColorization`, 设置这个选项为 `disabled`

**Comment by fisheva** [comment]
奇怪，你居然没有这个选项，难道是搜索文字带空格了吗？
你用的是什么版本的VSCode？...或许更新下VSCode？
![企业微信截图_20230414151750](https://user-images.githubusercontent.com/17448419/231971831-5b0f3dc8-c5bb-4b99-afc4-35dce26fdda7.png)

**Comment by MrFlyHouse** [comment]
> 奇怪，你居然没有这个选项，难道是搜索文字带空格了吗？ 你用的是什么版本的VSCode？...或许更新下VSCode？ ![企业微信截图_20230414151750](https://user-images.githubusercontent.com/17448419/231971831-5b0f3dc8-c5bb-4b99-afc4-35dce26fdda7.png)

并没有空格而且也用的是1.77.3版本的T_T
目前我能发现的解决办法只有禁用/卸载Babel JavaScript扩展了
您的enhancedColorization配置项是在Babel扩展下的么？之前您的截图写的是C/C++下的
![vscodeVersion](https://user-images.githubusercontent.com/102533859/231972550-e26e9527-85fa-4cb9-9261-2078a3847ce9.png)

**Comment by fisheva** [comment]
哦 原来这个`enhancedColorization`选项只有在安装C/C++插件后才有吗？...我一直以为这是VSCode的通用设置。那我确实还不知道Babel怎么处理...以前有用户问过，最后他的解决方式是卸载Babel...

**Comment by MrFlyHouse** [comment]
> 哦 原来这个`enhancedColorization`选项只有在安装C/C++插件后才有吗？...我一直以为这是VSCode的通用设置。那我确实还不知道Babel怎么处理...以前有用户问过，最后他的解决方式是卸载Babel......

嗯嗯，那我目前也只能先停用Babel了
看Babel的市场页面也没有任何说关于配置Babel的内容，扩展选项卡里Babel也没有Extension Settings，怀疑开发者是直接将代码高亮着色与错误检查整合在一起并且不允许任何人设置了

**Comment by fisheva** [comment]
谢谢你！你的反馈修正了我一个长久以来的错误认知。我的README文档要改了 2333
