### ISSUE TITLE
Publish to open-vsx.org - VSCodium

### ISSUE THREAD

**Issue by ibrahimbayyinah** [fisheva/Eva-Theme#92]
Firstly, thank you to the contributors for making this beautiful theme.

I want to ask if you could publish it to [open-vsx.org](https://open-vsx.org) such that it could be installed in [VSCodium](https://vscodium.com). The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks in advance!

**Comment by fisheva** [comment]
Hi, @ibrahimbayyinah 

I just found out about this editor. I just published, now you can use the Eva Theme on VSCodium.

**Comment by ibrahimbayyinah** [comment]
@fisheva amazing, thanks a lot!

PS: You should give VSCodium a try if you want. It is basically VS Code but without telemetry.
