### ISSUE TITLE
[FEATURE] - NEOVIM Support ⌨

### ISSUE THREAD

**Issue by WillKirkmanM** [fisheva/Eva-Theme#93]
Would love to see this theme integrated for Neovim!

**Comment by fisheva** [comment]
Hi, @WillKirkmanM

Unfortunately, I am not familiar with this Neovim as I don't use it personally. However, I suggest that you create a new repository under the [Eva Theme organization](https://github.com/Eva-Theme) and develop the Neovim Eva Theme.

Once you have completed your project,  I will be happy to promote it on the Eva Theme README.

**Comment by sharpchen** [comment]
hi, @fisheva, I am tinkering the neovim version(see: [Eva-Theme.nvim](https://github.com/sharpchen/Eva-Theme.nvim)), I wonder how to move it under the organization?
