### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by CoffeeChaton** [fisheva/Eva-Theme#94]
![r](https://github.com/fisheva/Eva-Theme/assets/63182963/ee6f00cd-e9ec-4f74-92ac-aec2a1eeeac4)

the folder `.github` and `.history` not need to be packaged to market.

the `vsce package` can use the [.vscodeignore](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#using-.vscodeignore) to ignore it.

**Comment by fisheva** [comment]
Thanks! @CoffeeChaton 

That's very useful! Updated in 2.0.0 version.
