### ISSUE TITLE
[feat] support `log.tmLanguage.json`

### ISSUE THREAD

**Issue by CoffeeChaton** [fisheva/Eva-Theme#95]
**Describe what you want**

| levels      | desired color      | textmate scopes |
| :---------- | :----------------- | :-------------- |
| `[info]`    | green              | log.info        |
| `[warning]` | yellow or dark red | log.warning     |
| `[error]`   | red or bright red  | log.error       |

the [vscode log.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/log/syntaxes/log.tmLanguage.json) is vscode extending default syntax.

exp

```typescript
// extension.ts

export function activate(context: vscode.ExtensionContext): void {
    const logExp: vscode.LogOutputChannel = vscode.window.createOutputChannel('exp', { log: true });
    logExp.info('log msg');
    logExp.warn('warn msg');
    logExp.error('error msg');
}
```

![info](https://github.com/fisheva/Eva-Theme/assets/63182963/48429011-46f1-4756-952f-7471add8574f)
![warning](https://github.com/fisheva/Eva-Theme/assets/63182963/036d3076-6fa0-4931-8c68-6a182a3de072)
![error](https://github.com/fisheva/Eva-Theme/assets/63182963/26ad9d3a-bea7-4205-aa7c-bb4c0e0d99ae)

**Comment by fisheva** [comment]
Thanks! I just knew that the text here could be colored. Updated in 2.0.0 version. 

Can you tell me how to print the text on your image in the out window?

**Comment by CoffeeChaton** [comment]
![x0](https://github.com/fisheva/Eva-Theme/assets/63182963/c2760541-3cc0-46d0-8507-f1c6b83b893b)

you need to select output name

```TypeScript
// extension.ts
export function activate(context: vscode.ExtensionContext): void {
    const logExp = vscode.window.createOutputChannel('exp', { log: true });
    ;                                                 ^^^ Output name
}
```

and <https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector>
