### ISSUE TITLE
Full code colorization support for `.dib` files

### ISSUE THREAD

**Issue by UPIMMUNITY** [fisheva/Eva-Theme#96]
### What is a `.dib` file?
`.dib` is a format for representing notebook content, just like `.ipynb` for python. `.dib` is for some other languages for example `C#`, `JavaScript` based on .NET Interactive.

### What extension I am using?
I am using [Polyglot Notebook](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode) writing `C#` code. This extension supports both `.dib` and `.ipynb`, but the syntax highlighting is not working properly with `.dib`.
### Screenshot

Working with `.ipynb` looks fine.
![image](https://github.com/fisheva/Eva-Theme/assets/77432836/9ae7a5af-21eb-41c1-84ed-3df59a7375e6)

Working with `.dib` when semantic highlighting is enabled.
![image](https://github.com/fisheva/Eva-Theme/assets/77432836/a9338252-de30-4e6f-b882-cd644d1312d4)

Working with `.dib` when semantic highlighting is disabled.
![image](https://github.com/fisheva/Eva-Theme/assets/77432836/feddbaf2-25df-4c42-8784-b020f066d691)

### Code Snippet

```csharp
public static double Closure(((double, double)[] b, (double, double)[] f) tuple) {
        var l = tuple.b.Zip(tuple.f, (x, y) => (backward:x, forward:y));
        return l.Select(x => {
            var f = x.backward.Item1 - x.forward.Item1;
            var s = x.backward.Item1 - x.forward.Item2;
            return (f + s) / 2;
        }).Sum();
}
```

**Comment by fisheva** [comment]
Hi, @UPIMMUNITY 

Sorry, I didn't write scope coloring rules specifically for `.ipynb` files, and I can't write scope coloring rules to support `.dib` files. They are not programming languages. I can't view the scope values of code blocks in `.dib` files.

All theme plugins add color to characters based on their scope value. All characters's scope value is given by VSCode. You can check them by pressing Ctrl+Shift+P (Windows) or Cmd+Shift+P (Mac) and selecting Inspect Editor Tokens and Scopes.

![企业微信截图_20230524191111](https://github.com/fisheva/Eva-Theme/assets/17448419/d3f680f4-0e1f-4557-9390-6e8e9bf73365)

I feel like you got the logic wrong. It's not the theme that needs to support `.dib` files, but `.dib` files need to add the feature of importing code themes for display. So you may need to raise an issue under the Polyglot Notebook plugin.

**Comment by UPIMMUNITY** [comment]
@fisheva I see, you're right. Nothing is colorized without semantic highlighting.
