### ISSUE TITLE
idea需要你

### ISSUE THREAD

**Issue by breeze-chw** [fisheva/Eva-Theme#97]
这不赶快适配上idea，颜色太舒服了

**Comment by LemonStudent** [comment]
这个配色真的很不错，不知道啥时候可以在IDEA中使用到

**Comment by fisheva** [comment]
IDEA的主题制作文档冗长难懂，经常被劝退...还在阅读尝试中...

**Comment by FTLLOVE** [comment]
idea确实需要你

**Comment by fisheva** [comment]
新回复参见[issue 120](https://github.com/fisheva/Eva-Theme/issues/120)
