### ISSUE TITLE
We need diff/patch file support!

### ISSUE THREAD

**Issue by FelixDai** [fisheva/Eva-Theme#98]
As the title.

个人觉得如果这么棒的 theme 不支持 diff/patch 格式实在是太可惜了

**Comment by fisheva** [comment]
网上搜的都换乱, 给个详尽的教程? 或者您提个PR?

**Comment by FelixDai** [comment]
> 网上搜的都好乱, 给个详尽的教程? 或者您提个PR?

周末研究研究
